### PR TITLE
WIP: possibly mark bitwuzla-cxx.0.{2,3,4}.0 as unavailable

### PR DESCRIPTION
**Pull request by shonfeder**
These showed up as a failing revdep in https://github.com/ocaml/opam-repository/pull/29189

[bitwuzla-cxx.0.2.0 (failed: 'replace' is not a member of 'std')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/6caba29379107c345f957d6faf6186749fa27569/variant/compilers,4.14,dune.3.21.0~alpha5,revdeps,bitwuzla-cxx.0.2.0)
[bitwuzla-cxx.0.3.0 (failed: 'replace' is not a member of 'std')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/6caba29379107c345f957d6faf6186749fa27569/variant/compilers,4.14,dune.3.21.0~alpha5,revdeps,bitwuzla-cxx.0.3.0)
[bitwuzla-cxx.0.4.0 (failed: 'abs' is not a member of 'std')](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/6caba29379107c345f957d6faf6186749fa27569/variant/compilers,4.14,dune.3.21.0~alpha5,revdeps,bitwuzla-cxx.0.4.0)

Local testing indicated the packages may be broken, so I'd like to run one thru CI.

### CODE REVIEW

**Comment by shonfeder** [comment]
CI is not running?
