### PR TITLE
aperf.0.1 - via opam-publish

### PR DESCRIPTION
**Pull request by philipdexter**
OCaml tools for loop perforation

---
* Homepage: http://github.com/philipdexter/aperf
* Source repo: http://git.phfilip.com/aperf
* Bug tracker: http://github.com/philipdexter/aperf/issues

---
### opam-lint failures
- **WARNING** 97 long description unspecified

---

---
v0.1 2016-07-26
---------------

Initial release.
Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by yallop** [comment]
The build is [failing on OCaml 4.02](https://travis-ci.org/ocaml/opam-repository/jobs/147531376):

```
# File "aperf/aperf.ml", line 138, characters 39-51:
# Error: Unbound value String.equal
# Command exited with code 2.
```

because [`String.equal` was introduced in OCaml 4.03](https://github.com/ocaml/ocaml/blob/38c3db40c7533aece24279317dba28f7ce7d1f5a/stdlib/string.mli#L283).  One fix is to add a version constraint

````
available: [ ocaml-version >= "4.03.0" ]
```

**Comment by philipdexter** [comment]
Thanks, I'll probably try to make it work with 4.02 and try again
