### PR TITLE
core_unix: Disable the package on OCaml >= 5.3 on non-x86_64 platforms

### PR DESCRIPTION
**Pull request by kit-ty-kate**
see janestreet/core_unix#14

### CODE REVIEW

**Comment by yawaramin** [comment]
Duplicate of #27737 ?

**Comment by kit-ty-kate** [comment]
> Duplicate of #27737 ?

looking into it, in spirit i suppose yeah. But the proposed fix is different. The fix proposed in #27737 is wrong: `core_unix` does work on 5.3 if you're on a x86_64 machine (with exception of non-glibc users, which opam cannot filter for at the moment, see https://github.com/ocaml/opam/issues/6345)

**Comment by Leonidas-from-XIV** [comment]
> The fix proposed in https://github.com/ocaml/opam-repository/pull/27737 is wrong: core_unix does work on 5.3 if you're on a x86_64 machine

The failing build quoted in #27737 is on Fedora 41 x86_64, so very much a glibc machine. 

For the non-glibc failure I've opened #27736 (which just targets Alpine, but that's the only non-glibc distribution we currently test on so close enough)

**Comment by mseri** [comment]
This seems to fail still on x86_64:

- [core_unix.v0.17.0 (failed: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/18a30f1534ecda31357ccef7b9e06a5892ca86cf/variant/distributions,alpine-3.21-ocaml-5.3,core_unix.v0.17.0)

- [core_unix.v0.17.0 (failed: implicit declaration of function ‘atomic_load_acquire’ [-Wimplicit-function-declaration])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/18a30f1534ecda31357ccef7b9e06a5892ca86cf/variant/distributions,archlinux-ocaml-5.3,core_unix.v0.17.0)

- [core_unix.v0.17.0 (failed: implicit declaration of function 'atomic_load_acquire' [-Wimplicit-function-declaration])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/18a30f1534ecda31357ccef7b9e06a5892ca86cf/variant/distributions,debian-testing-ocaml-5.3,core_unix.v0.17.0)

- [core_unix.v0.17.0 (failed: implicit declaration of function 'atomic_load_acquire' [-Wimplicit-function-declaration])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/18a30f1534ecda31357ccef7b9e06a5892ca86cf/variant/distributions,debian-unstable-ocaml-5.3,core_unix.v0.17.0)

- [core_unix.v0.17.0 (failed: implicit declaration of function 'atomic_load_acquire' [-Wimplicit-function-declaration])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/18a30f1534ecda31357ccef7b9e06a5892ca86cf/variant/distributions,fedora-40-ocaml-5.3,core_unix.v0.17.0)

- [core_unix.v0.17.0 (failed: implicit declaration of function 'atomic_load_acquire' [-Wimplicit-function-declaration])](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/18a30f1534ecda31357ccef7b9e06a5892ca86cf/variant/distributions,fedora-41-ocaml-5.3,core_unix.v0.17.0)

**Comment by mseri** [comment]
Nothing to be sorry about. In this case it would be useful to be able to check on gcc 14, but I am not sure we have a way to do it. I think it may be easier just to disable it with 5.3. What do you think @kit-ty-kate ?

**Comment by kit-ty-kate** [comment]
Yes i already reviewed/approved the PR in https://github.com/ocaml/opam-repository/pull/27737#pullrequestreview-2760828563
