### PR TITLE
[new release] yocaml (12 packages) (2.0.0)

### PR DESCRIPTION
**Pull request by xvw**
Core engine of the YOCaml Static Site Generator

- Project page: <a href="https://github.com/xhtmlboi/yocaml">https://github.com/xhtmlboi/yocaml</a>

#### yocaml

- Complete reconstruction of the YOCaml core (by [xhtmlboi](https://github.com/xhtmlboi), [xvw](https://github.com/xvw), [gr-im](https://github.com/gr-im), [mspwn](https://github.com/mspwn), [dinosaure](https://github.com/dinosaure), [maiste](https://github.com/maiste) and [hakimba](https://github.com/Hakimba))

#### yocaml_cmarkit

- Second release (by [maiste](https://github.com/maiste) and [xvw](https://github.com/xvw))

#### yocaml_eio

- First release (by [xvw](https://github.com/xvw), [dinosaure](https://github.com/dinosaure), [hannesm](https://github.com/hannesm), and [xhtmlboi](https://github.com/xhtmlboi))

#### yocaml_git

- First release (by [dinosaure](https://github.com/dinosaure) and [xhtmlboi](https://github.com/xhtmlboi))

#### yocaml_jingoo

- Second release (by [xhtmlboi](https://github.com/xhtmlboi), [mspwn](https://github.com/mspwn) and [xvw](https://github.com/xvw))

#### yocaml_mustache

- Second release (by [xhtmlboi](https://github.com/xhtmlboi), [mspwn](https://github.com/mspwn) and [xvw](https://github.com/xvw))

#### yocaml_omd

- Second release (by [xhtmlboi](https://github.com/xhtmlboi), [mspwn](https://github.com/mspwn) and [xvw](https://github.com/xvw))

#### yocaml_otoml

- First release (by [xvw](https://github.com/xvw))

#### yocaml_syndication

- Second release (by [xvw](https://github.com/xvw), [mspwn](https://github.com/mspwn), [gr-im](https://github.com/gr-im) and [tim-ats-d](https://github.com/Tim-ats-d))

#### yocaml_unix

- Second release (by [xvw](https://github.com/xvw), [dinosaure](https://github.com/dinosaure), [hannesm](https://github.com/hannesm), and [xhtmlboi](https://github.com/xhtmlboi))

#### yocaml_yaml

- Second release (by [xhtmlboi](https://github.com/xhtmlboi), [mspwn](https://github.com/mspwn) and [xvw](https://github.com/xvw))

### CODE REVIEW

**Comment by mseri** [comment]
Fails with
```
#=== ERROR while compiling yocaml.2.0.0 =======================================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.5.1.1 | file:///home/opam/opam-repository
# path                 ~/.opam/5.1/.opam-switch/build/yocaml.2.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p yocaml -j 31 @install
# exit-code            1
# env-file             ~/.opam/log/yocaml-7-6c17e5.env
# output-file          ~/.opam/log/yocaml-7-6c17e5.out
### output ###
# File "test/yocaml-expect/dune", line 7, characters 7-17:
# 7 |   (pps ppx_expect)))
#            ^^^^^^^^^^
# Error: Library "ppx_expect" not found.
# -> required by library "yocaml_expect_test" in
#    _build/default/test/yocaml-expect
# -> required by _build/default/META.yocaml
# -> required by _build/install/default/lib/yocaml/META
# -> required by _build/default/yocaml.install
# -> required by alias install
```
Looks like the yocaml-expect tests is attempted to build always, also when not compiling for tests, not sure why

**Comment by xvw** [comment]
Yes, it is weird :/

**Comment by xvw** [comment]
A difference with regular tests is that it is defined as a library

**Comment by xvw** [comment]
@mseri I try to fix the CI (adding ppx_expect as dependency for every sub-packages)

**Comment by xvw** [comment]
Not working on `5.3.0~alpha` seems not an issue (I'll fix the boundaries soon) since we are using at least one ppx but the global error, on every valid candidate: `Error: Unbound value "triple"` seems very weird to me.

**Comment by dinosaure** [comment]
`triple` appeared only since `alcotest.1.3.0`, you should add a constraint on your OPAM file (no necessary to redo a tarball - you can directly add the constraint in this PR & do the change on your Git repository).

**Comment by dinosaure** [comment]
Seems good, thanks!
