### PR TITLE
[new release] printbox (5 packages) (0.12)

### PR DESCRIPTION
**Pull request by c-cube**
Allows to print nested boxes, lists, arrays, tables in several formats

- Project page: <a href="https://github.com/c-cube/printbox">https://github.com/c-cube/printbox</a>

##### CHANGES:

- Remove fallback to and dependency on `printbox-html` from `printbox-md` (@lukstafi)
- introduce notion of extensions (@lukstafi)
- add `printbox-ext-plot` extension for text and HTML plots (@lukstafi)
- feat: add `?stretch` param to `frame`

- fix c-cube/printbox#45, problem with nested frames

### CODE REVIEW

**Comment by mseri** [comment]
This is a known issue with 5.0.0, right?
```
#=== ERROR while compiling printbox-html.0.12 =================================#
# context              2.4.0~alpha1~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://github.com/c-cube/printbox/releases/download/v0.12/printbox-0.12.tbz)
# path                 ~/.opam/5.0/.opam-switch/build/printbox-html.0.12
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p printbox-html -j 39 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/printbox-html-7-be3a41.env
# output-file          ~/.opam/log/printbox-html-7-be3a41.out
### output ###
# File "README.md", line 1, characters 0-0:
# /usr/bin/git --no-pager diff --no-index --color=always -u _build/default/README.md _build/default/.mdx/README.md.corrected
# diff --git a/_build/default/README.md b/_build/default/.mdx/README.md.corrected
# index 73867b8..b420706 100644
# --- a/_build/default/README.md
# +++ b/_build/default/.mdx/README.md.corrected
# @@ -156,18 +156,11 @@ can be used as a default printer for boxes.
#  
#  ```ocaml
#  # #install_printer PrintBox_text.pp;;
# +Cannot find type Topdirs.printer_type_new.
#  # PrintBox.(frame @@ frame @@ init_grid ~line:3 ~col:2 (fun ~line:i ~col:j -> sprintf "%d.%d" i j));;
# -- : B.t =
# -┌─────────┐
# -│┌───┬───┐│
# -││0.0│0.1││
# -│├───┼───┤│
# -││1.0│1.1││
# -│├───┼───┤│
# -││2.0│2.1││
# -│└───┴───┘│
# -└─────────┘
# +- : B.t = <abstr>
#  # #remove_printer PrintBox_text.pp;;
# +Cannot find type Topdirs.printer_type_new.
#  ```
#  
#  Note that this pretty-printer plays nicely with `Format` boxes:
```

**Comment by c-cube** [comment]
Oh, yes, I've seen this before. If it works fine on 5.1 or 5.2 I'd just ignore it :)

**Comment by mseri** [comment]
Thanks

**Comment by c-cube** [comment]
Thank you!
