### PR TITLE
Make codept available for ocaml >= 4.04.0

### PR DESCRIPTION
**Pull request by Khady**
Codept is not available for ocaml 4.04.1 because of the requirement of the exact version 4.04.0.

cc @Octachron

### CODE REVIEW

**Comment by avsm** [comment]
Looks like it fails to compile on 4.04.1

```
# + /usr/bin/ocamlc.opt -c -I /usr/lib/ocaml/ocamlbuild -bin-annot -safe-string -short-paths -no-alias-deps -strict-formats -thread -strict-sequence -w A-44-42-45-40-4-41-6-48-30@8 -I ocamlbuild_plugin -I precomputed -I lib -I full -I tests -I lib/sexp -o ocamlbuild_plugin/codept_ocamlbuild.cmo ocamlbuild_plugin/codept_ocamlbuild.ml
# File "ocamlbuild_plugin/codept_ocamlbuild.ml", line 11, characters 10-30:
# Error: Unbound value String.split_on_char
# Command exited with code 2.
```

**Comment by Octachron** [comment]
This error (and the one for 4.05) seems strange since String.split_on_char is available in the stdlib for version ≥4.04.0 .

**Comment by avsm** [comment]
It's an ocamlbuild plugin, so it's probably the overridden `String` module provided as part of the ocamlbuild API that hasnt been updated for the new functions

**Comment by Octachron** [comment]
Good point. I will fix this blunder and release a minor update.
@Khady : Thanks for the reminder.

**Comment by Khady** [comment]
Oh, I tried to pin the package to test the compilation but I actually
compiled master instead of the revision that is released. Sorry for the
noise.

**Comment by Octachron** [comment]
@Khady, on my side, this was a nice reminder that I had a compatibility release planned, cf. https://github.com/ocaml/opam-repository/pull/9519, so thanks.

**Comment by avsm** [comment]
Closing this in favour of #9519, please reopen if it should still be considered for merge.
