### ISSUE TITLE
Old domainslib cannot compile with released ocaml 5.0

### ISSUE THREAD

**Issue by mseri** [ocaml/opam-repository#23790]
Should we mark them as unavailable?

```

#=== ERROR while compiling domainslib.0.3.0 ===================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/domainslib.0.3.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p domainslib -j 127
# exit-code            1
# env-file             ~/.opam/log/domainslib-7-83a762.env
# output-file          ~/.opam/log/domainslib-7-83a762.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/.domainslib.objs/byte -no-alias-deps -open Domainslib__ -o lib/.domainslib.objs/byte/domainslib__Ws_deque.cmo -c -impl lib/ws_deque.ml)
# File "lib/ws_deque.ml", line 192, characters 8-29:
# 192 |         Domain.Sync.cpu_relax ();
#               ^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Domain.Sync
```

ping @samoht

**Comment by kayceesrk** [comment]
>  it can probably just depend on the 4.14+domains compiler I suspect.

Agreed. @Sudha247 has been maintaining domainslib. Sudha, please can you have a look?

**Comment by Sudha247** [comment]
I had a quick look - `Domain.Sync.cpu_relax` was deprecated in `4.12.0+domains` in favour of `Domain.cpu_relax`. Previous versions of the multicore compiler are not available in `opam-repository`. We should just mark it as unavailable, I think. Will send in a patch.

**Comment by hannesm** [comment]
This was addressed in 3c307ced501800425da8376579f3542fe0da8b9e, thanks to @kit-ty-kate
