### PR TITLE
[new release] lablgtk3-gtkspell3, lablgtk3-sourceview3 and lablgtk3 (3.0.beta7)

### PR DESCRIPTION
**Pull request by garrigue**
OCaml interface to GTK+3

- Project page: <a href="https://github.com/garrigue/lablgtk">https://github.com/garrigue/lablgtk</a>
- Documentation: <a href="https://garrigue.github.io/lablgtk/lablgtk3-gtkspell3">https://garrigue.github.io/lablgtk/lablgtk3-gtkspell3</a>

##### CHANGES:

2019.11.25 [Jacques]
  * Split source code in terms of packages (garrigue/lablgtk#77) [Emilio]
  * Update README to better document build system (garrigue/lablgtk#80) [Emilio]
  * Switch from camlp4 to camlp5 (required for 4.09)
  * Add `[@warnerror "-3"]` to call to `Obj.truncate`
  * Move `COPYING` to `LICENSE`

2019.09.25 [Jacques]
  * Fix several gtk3 examples, and remove some obsolete ones
   (garrigue/lablgtk#84) [Martin de Mello]
  * Disable -warn-error 3 in src/dune, because of Obj.truncate

2019.09.23 [Martin de Mello]
  * Add the LinkButton activate-link signal garrigue/lablgtk#83

2019.08.12 [Emilio J. Gallego Arias]
  * Reorganize source code, move orphaned files to unsupported,
    bump to Dune >= 1.6
2019.08.12 [Emilio J. Gallego Arias]
  * Remove stale makefiles, lablgtk must be built using Dune now.

2019.07.07 [Emilio J. Gallego Arias]
  * Include extended Cairo Support from garrigue/lablgtk#33 in the Dune build.

2019.06.27 [Anton Kochkov]
  * Upgrade CI to OCaml 4.08

### CODE REVIEW

**Comment by garrigue** [comment]
Only two distributions fail, and only for gtkspell3:
* for Alpine, gtkspell3-dev is only available on edge
* CentOS 7 only has gtkspell-3.0.3, and we require 3.0.4

**Comment by XVilka** [comment]
By the way, CentOS 8 was released a while ago, it might make sense to update it in the CI too @kit-ty-kate

**Comment by kit-ty-kate** [comment]
Do you have any idea what's wrong here?
```
l
# Linking  bin/why3ide.opt
# /usr/bin/ld: /home/opam/.opam/4.09/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o): in function `caml_pango_cairo_font_map_new_for_font_type':
# /home/opam/.opam/4.09/.opam-switch/build/lablgtk3.3.0.beta7/_build/default/src/cairo_pango_stubs.c:85: undefined reference to `caml_cairo_font_type_val'
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
# make: *** [Makefile:2230: bin/why3ide.opt] Error 2
```

**Comment by garrigue** [comment]
This looks like cairo2 not included at link time. 
I'm not sure whose responsability it is. At the opam level lablgtk3 registers a dependency on cairo2, but I suppose the user should include it explicitly in the link when needed.

**Comment by kit-ty-kate** [comment]
Mh I just tried locally and it `why3-ide.1.2.1` compiles with `lablgtk3.3.0.beta6` but not with `beta7`. I think this is worth stopping this release and investigating. I don't really want to stop people from being able to install why3-ide easily:
```
opam@b6b42e04b79f:~/opam-repository$ opam depext -iy why3-ide lablgtk3
[...]
The following actions will be performed:                                                                                                                                                                                                       
  - install conf-m4              1         [required by ocamlfind]                                                                                                                                                                             
  - install conf-pkg-config      1.1       [required by conf-gtk3]                                                                                                                                                                             
  - install dune                 2.0.0     [required by lablgtk3]                                                                                                                                                                              
  - install ocamlbuild           0.14.0    [required by menhir]                                                                                                                                                                                
  - install ocamlfind            1.8.1     [required by why3-ide]                                                                                                                                                                              
  - install conf-gtksourceview3  0+1       [required by lablgtk3-sourceview3]                                                                                                                                                                  
  - install conf-gtk3            18        [required by lablgtk3]                                                                                                                                                                              
  - install conf-cairo           1         [required by cairo2]                                                                                                                                                                                
  - install dune-private-libs    2.0.0     [required by dune-configurator]                                                                                                                                                                     
  - install num                  1.3       [required by why3]                                                                                                                                                                                  
  - install menhir               20190924  [required by why3]                                                                                                                                                                                  
  - install dune-configurator    2.0.0     [required by lablgtk3]                                                                                                                                                                              
  - install why3                 1.2.1     [required by why3-ide]                                                                                                                                                                              
  - install cairo2               0.6.1     [required by lablgtk3]                                                                                                                                                                              
  - install lablgtk3             3.0.beta6                                                                                                                                                                                                     
  - install lablgtk3-sourceview3 3.0.beta6 [required by why3-ide]
  - install why3-ide             1.2.1
===== 17 to install =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[cairo2.0.6.1] found in external cache at /home/opam/opam-repository/cache
[dune-configurator.2.0.0] found in external cache at /home/opam/opam-repository/cache
[dune-private-libs.2.0.0] found in cache
[dune.2.0.0] downloaded from https://github.com/mefyl/dune/archive/feature/cache-copy-mode.tar.gz
[lablgtk3.3.0.beta6] found in external cache at /home/opam/opam-repository/cache
[menhir.20190924] found in external cache at /home/opam/opam-repository/cache
[num.1.3] found in external cache at /home/opam/opam-repository/cache
[lablgtk3-sourceview3.3.0.beta6] found in external cache at /home/opam/opam-repository/cache
[ocamlbuild.0.14.0] found in external cache at /home/opam/opam-repository/cache
[ocamlfind.1.8.1] found in external cache at /home/opam/opam-repository/cache
[why3.1.2.1] found in external cache at /home/opam/opam-repository/cache
[why3-ide.1.2.1] found in external cache at /home/opam/opam-repository/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed conf-m4.1
-> installed conf-pkg-config.1.1
-> installed conf-cairo.1
-> installed conf-gtk3.18
-> installed conf-gtksourceview3.0+1
-> installed ocamlfind.1.8.1
-> installed num.1.3
-> installed ocamlbuild.0.14.0
-> installed dune.2.0.0
-> installed dune-private-libs.2.0.0
-> installed menhir.20190924
-> installed dune-configurator.2.0.0
-> installed cairo2.0.6.1
-> installed lablgtk3.3.0.beta6                                                                                                                                                                                                            
-> installed why3.1.2.1                                                                                                                                                                                                                        
-> installed lablgtk3-sourceview3.3.0.beta6                                                                                                                                                                                                    
-> installed why3-ide.1.2.1                                                                                                                                                                                                                    
Done.                                                                                                                                                                                                                                          
# Run eval $(opam env) to update the current shell environment                                                                                                                                                                                 
opam@b6b42e04b79f:~/opam-repository$ git pull git://github.com/garrigue/opam-repository.git release-lablgtk3-3.0.beta7                                                                                                                         
remote: Enumerating objects: 5, done.                                                                                                                                                                                                          
remote: Counting objects: 100% (5/5), done.                                                                                                                                                                                                    
remote: Total 12 (delta 5), reused 5 (delta 5), pack-reused 7                                                                                                                                                                                  
Unpacking objects: 100% (12/12), done.                                                                                                                                                                                                         
From git://github.com/garrigue/opam-repository                                                                                                                                                                                                 
 * branch                  release-lablgtk3-3.0.beta7 -> FETCH_HEAD                                                                                                                                                                            
Merge made by the 'recursive' strategy.                                                                                                                                                                                                        
 packages/lablgtk3-gtkspell3/lablgtk3-gtkspell3.3.0.beta7/opam     | 49 +++++++++++++++++++++++++++++++++++++++++++++++++                                                                                                                      
 packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam | 37 +++++++++++++++++++++++++++++++++++++                                                                                                                                  
 packages/lablgtk3/lablgtk3.3.0.beta7/opam                         | 37 +++++++++++++++++++++++++++++++++++++                                                                                                                                  
 3 files changed, 123 insertions(+)                                                                                                                                                                                                            
 create mode 100644 packages/lablgtk3-gtkspell3/lablgtk3-gtkspell3.3.0.beta7/opam                                                                                                                                                              
 create mode 100644 packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam                                                                                                                                                          
 create mode 100644 packages/lablgtk3/lablgtk3.3.0.beta7/opam                                                                                                                                                                                  
opam@b6b42e04b79f:~/opam-repository$ opam update default                                                                                                                                                                                       
                                                                                                                                                                                                                                               
<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>                                                                                                                                                               
[default] synchronised from file:///home/opam/opam-repository                                                                                                                                                                                  
Now run 'opam upgrade' to apply any package updates.                                                                                                                                                                                           
opam@b6b42e04b79f:~/opam-repository$ opam upgrade                                                                                                                                                                                              
The following actions will be performed:                         
  - upgrade   lablgtk3             3.0.beta6 to 3.0.beta7
  - upgrade   lablgtk3-sourceview3 3.0.beta6 to 3.0.beta7
  - recompile why3-ide             1.2.1                  [uses lablgtk3, lablgtk3-sourceview3]
===== 1 to recompile | 2 to upgrade =====                                       
Do you want to continue? [Y/n] y                                          
                                                                                     
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[why3-ide.1.2.1] found in cache                                                                  
[lablgtk3-sourceview3.3.0.beta7] downloaded from https://github.com/garrigue/lablgtk/releases/download/3.0.beta7/lablgtk3-3.0.beta7.tbz
[lablgtk3.3.0.beta7] downloaded from https://github.com/garrigue/lablgtk/releases/download/3.0.beta7/lablgtk3-3.0.beta7.tbz
                                                                     
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>            
-> removed   why3-ide.1.2.1                                                    
-> removed   lablgtk3-sourceview3.3.0.beta6                                  
-> removed   lablgtk3.3.0.beta6                                         
-> installed lablgtk3.3.0.beta7
-> installed lablgtk3-sourceview3.3.0.beta7
[ERROR] The compilation of why3-ide failed at "/usr/bin/make -j71 ide".

#=== ERROR while compiling why3-ide.1.2.1 =====================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | file:///home/opam/opam-repository
# path        ~/.opam/4.09.0/.opam-switch/build/why3-ide.1.2.1
# command     /usr/bin/make -j71 ide
# exit-code   2
# env-file    ~/.opam/log/why3-ide-16910-708d92.env
# output-file ~/.opam/log/why3-ide-16910-708d92.out
### output ###
# [...]
# Ocamlopt src/ide/gtkcompat.ml
# Ocamlopt src/ide/ide_utils.ml
# Ocamlopt src/ide/gconfig.ml
# Ocamlc   src/ide/why3ide.ml
# Ocamlopt src/ide/why3ide.ml
# Linking  bin/why3ide.opt
# /usr/bin/ld: /home/opam/.opam/4.09.0/lib/lablgtk3/liblablgtk3_stubs.a(cairo_pango_stubs.o): in function `caml_pango_cairo_font_map_new_for_font_type':
# /home/opam/.opam/4.09.0/.opam-switch/build/lablgtk3.3.0.beta7/_build/default/src/cairo_pango_stubs.c:85: undefined reference to `caml_cairo_font_type_val'
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
# make: *** [Makefile:2230: bin/why3ide.opt] Error 2
```

**Comment by kit-ty-kate** [comment]
> This looks like cairo2 not included at link time.
> I'm not sure whose responsability it is. At the opam level lablgtk3 registers a dependency on cairo2, but I suppose the user should include it explicitly in the link when needed.

even with C libraries, I don't think users of libraries should ever bother tracking every dependencies their dependencies use, explicit link should never be needed, if a library is used by yours then it should be linked to it.

**Comment by ejgallego** [comment]
I'll have a look, it seems that some stub may be indeed missing in the `cairo_pango` object we use.

I guess we should add some cases to our test suite.

**Comment by ejgallego** [comment]
This is a bug in why3, their IDE build script is bogus and doesn't correctly include the dependencies of lablgtk3 correctly as for example provided by `ocamlfind`.

**Comment by kit-ty-kate** [comment]
Oh, indeed. cc @silene. The previous commit should stop why3-ide from failing. Let's wait for a last pass of CI and this should be good to go.

File: packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+dev-repo: "git+https://github.com/garrigue/lablgtk.git"
+doc: "https://garrigue.github.io/lablgtk/lablgtk3-sourceview3"
+license: "LGPL with linking exception"
+
+depends: [
+  "ocaml"                {         >= "4.05.0"    }
+  "dune"                 { build & >= "1.6.0"
+                                 & != "1.7.0"
+                                 & != "1.7.1"     } # Due to dune/dune#1833
+  "lablgtk3"             {         >= "3.0.beta5" }
```
Comment (kit-ty-kate) [inline packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam]: This error seems to indicate that a slightly stricter constraint is needed here with either `{= version}` or something else.
```
#=== ERROR while compiling lablgtk3-sourceview3.3.0.beta7 =====================#
# context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.09.0 | pinned(https://github.com/garrigue/lablgtk/releases/download/3.0.beta7/lablgtk3-3.0.beta7.tbz)
# path                 ~/.opam/4.09/.opam-switch/build/lablgtk3-sourceview3.3.0.beta7
# command              ~/.opam/4.09/bin/dune build -p lablgtk3-sourceview3 -j 2
# exit-code            1
# env-file             ~/.opam/log/lablgtk3-sourceview3-25-023584.env
# output-file          ~/.opam/log/lablgtk3-sourceview3-25-023584.out
### output ###
#  dune_config src-sourceview3/cflag-gtksourceview-3.0.sexp,src-sourceview3/clink-gtksourceview-3.0.sexp
# Warning: Package name "gtksourceview-3.0 >= 3.18" contains invalid characters. Use Pkg_config.query_expr to construct proper queries
#       ocamlc src-sourceview3/ml_gtksourceview3.o (exit 2)
# (cd _build/default/src-sourceview3 && /home/opam/.opam/4.09/bin/ocamlc.opt -g -I /home/opam/.opam/4.09/lib/cairo2 -I /home/opam/.opam/4.09/lib/lablgtk3 -I /home/opam/.opam/4.09/lib/ocaml/threads -ccopt -pthread -ccopt -I/usr/include/gtksourceview-3.0 -ccopt -I/usr/include/libxml2 -ccopt -I/usr/include/gtk-3.0 -ccopt -I/usr/include/at-spi2-atk/2.0 -ccopt -I/usr/include/at-spi-2.0 -ccopt -I/usr/include/dbus-1.0 -ccopt -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -ccopt -I/usr/include/gtk-3.0 -ccopt -I/usr/include/gio-unix-2.0 -ccopt -I/usr/include/cairo -ccopt -I/usr/include/libdrm -ccopt -I/usr/include/pango-1.0 -ccopt -I/usr/include/harfbuzz -ccopt -I/usr/include/pango-1.0 -ccopt -I/usr/include/fribidi -ccopt -I/usr/include/atk-1.0 -ccopt -I/usr/include/cairo -ccopt -I/usr/include/pixman-1 -ccopt -I/usr/include/freetype2 -ccopt -I/usr/include/libpng16 -ccopt -I/usr/include/gdk-pixbuf-2.0 -ccopt -I/usr/include/libmount -ccopt -I/usr/include/blkid -ccopt -I/usr/include/uuid -ccopt -I/usr/include/glib-2.0 -ccopt -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -ccopt -Wno-deprecated-declarations -ccopt -g -o ml_gtksourceview3.o ml_gtksourceview3.c)
# ml_gtksourceview3.c:34:10: fatal error: wrappers.h: No such file or directory
#  #include <wrappers.h>
#           ^~~~~~~~~~~~
# compilation terminated.
```

Comment (ejgallego) [reply packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam]: > This error seems to indicate that a slightly stricter constraint is needed here with either `{= version}` or something else.

This problem is fixed in `lablgtk3` git, but manually. I'm not sure how the `version` field is supposed to be used; can we include it without adding a `version: NNN` top-level field to the opam file?

Comment (kit-ty-kate) [reply packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam]: the version field is optional (and usually unwanted/redundant in opam-repository). `version` inside constraints blocks will always point to the version of the package as defined by either a `version` field or a the name of the directory `packages/<package>/<package>.<version>/opam` in opam-repository.

Anyway, I can see that the constraint is set to `>= "3.0.beta6"` is it correct to use it here? I was mostly pointing out to `{= version}` as it is the simplest way to do it and doesn't require much thinking.

Comment (ejgallego) [reply packages/lablgtk3-sourceview3/lablgtk3-sourceview3.3.0.beta7/opam]: Yup thanks, we will use `{= version}`, see https://github.com/garrigue/lablgtk/pull/99

**Comment by ejgallego** [comment]
> Oh, indeed. cc @silene. The previous commit should stop why3-ide from failing. Let's wait for a last pass of CI and this should be good to go.

The fix for why3 makefile is easy, just add `-I lib/cairo2 cairo` to the linking flags, but it would be better if they used `ocamlfind` to query for the flags.

**Comment by kit-ty-kate** [comment]
I'm not too sure why this PR has outdated opam files compared to the upstream repository. It's a bit puzzling to me as the PR seems to have been opened using `dune-release` which should take care of that. @garrigue?

**Comment by kit-ty-kate** [comment]
Could you update this PR using the proper opam files? (I don't really know how to use dune-release but probably something like `dune-release publish` should do it). The constraints for dune are outdated as well (requires at least dune 1.8)

**Comment by ejgallego** [comment]
> I'm not too sure why this PR has outdated opam files compared to the upstream repository. It's a bit puzzling to me as the PR seems to have been opened using `dune-release` which should take care of that. @garrigue?

Upstream repos is ahead the release tag, we improved quite a few things; IMHO the current fixes should suffice until beta8 comes; note that the dependency on dune is correct [master tho depends on 1.8]

**Comment by kit-ty-kate** [comment]
Oh my bad. Thanks a lot!

**Comment by ejgallego** [comment]
Thanks a lot to you!!
