### PR TITLE
[new release] mmap (1.0.0)

### PR DESCRIPTION
**Pull request by diml**
File mapping functionality

- Project page: <a href="https://github.com/mirage/mmap">https://github.com/mirage/mmap</a>
- Documentation: <a href="https://mirage.github.io/mmap/">https://mirage.github.io/mmap/</a>

##### CHANGES:

Initial release.

### CODE REVIEW

**Comment by mseri** [comment]
`ocaml` 4.02 to 4.05 are failing on Travis and the CI. I only went to look at the CI and there seems to be a missing header:

```
=== ERROR while compiling mmap.1.0.0 =========================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/mirage/mmap/releases/download/1.0.0/mmap-1.0.0.tbz)
# path                 ~/.opam/4.03/.opam-switch/build/mmap.1.0.0
# command              ~/.opam/4.03/bin/dune build -p mmap -j 71
# exit-code            1
# env-file             ~/.opam/log/mmap-20-f4c236.env
# output-file          ~/.opam/log/mmap-20-f4c236.out
### output ###
#       ocamlc src/mmap.o (exit 2)
# (cd _build/default/src && /home/opam/.opam/4.03/bin/ocamlc.opt -g -ccopt -g -o mmap.o mmap.c)
# mmap.c:25:21: fatal error: caml/io.h: No such file or directory
#  #include <caml/io.h>
#                      ^
# compilation terminated.
#       ocamlc src/mmap_ba.o (exit 2)
# (cd _build/default/src && /home/opam/.opam/4.03/bin/ocamlc.opt -g -ccopt -g -o mmap_ba.o mmap_ba.c)
# mmap_ba.c:60:3: error: 'caml_ba_compare' undeclared here (not in a function)
#    caml_ba_compare,
#    ^~~~~~~~~~~~~~~
# mmap_ba.c:61:3: error: 'caml_ba_hash' undeclared here (not in a function)
#    caml_ba_hash,
#    ^~~~~~~~~~~~
# mmap_ba.c:62:3: error: 'caml_ba_serialize' undeclared here (not in a function)
#    caml_ba_serialize,
#    ^~~~~~~~~~~~~~~~~
# mmap_ba.c:63:3: error: 'caml_ba_deserialize' undeclared here (not in a function)
#    caml_ba_deserialize,
#    ^~~~~~~~~~~~~~~~~~~
```

**Comment by diml** [comment]
Ah indeed, I didn't test the build with OCaml < 4.05, but it seems that there are other issues. I'll fix these and open a new PR.
