### PR TITLE
OCaml: release of OCaml 5.4.1 and 4.14.3

### PR DESCRIPTION
**Pull request by Octachron**
This PR adds the release package for the two new bug fix releases for respectively OCaml 5.4 and OCaml 4.14 which contains essentially valuable and safe runtime fixes, and in the case of OCaml 5.4.1 a fix for restoring the support of `-pack` on macOS.

### CODE REVIEW

**Comment by MisterDA** [comment]
@Octachron maybe you made a mistake while copying files?
```
packages/ocaml/ocaml.4.14.3/ocaml.4.14.2/opam
packages/ocaml/ocaml.4.14.4/ocaml.4.14.2/opam
packages/ocaml/ocaml.5.4.1/ocaml.5.4.0/opam
packages/ocaml/ocaml.5.4.2/ocaml.5.4.0/opam
```
I could be wrong, but it seems there is a wrong second-level of versioned directories.

[(analysis) (failed: Unexpected path `"packages/ocaml/ocaml.4.14.3/ocaml.4.14.2/opam"` in packages directory (expecting `'packages/name/name.l.m.n/{opam,files/*}'`))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/da899e32ba9f5a71686f4b61c0688f42f8a35f26/variant/(analysis))

**Comment by Octachron** [comment]
This was indeed a mistake, which is now fixed.

**Comment by MisterDA** [comment]
```
# make[1]: Entering directory '/home/opam/.opam/5.4/.opam-switch/build/ocaml-base-compiler.4.14.3/runtime'
# gcc -c -O2 -fno-strict-aliasing -fwrapv -pthread -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g  -D_FILE_OFFSET_BITS=64 -DCAML_NAME_SPACE  -DCAMLDLLIMPORT=  -o sak.o sak.c
# In file included from sak.c:25:0:
# caml/misc.h:263:18: error: missing binary operator before token "("
#  #if __has_builtin(__builtin_expect) || defined(__GNUC__)
#                   ^
# make[1]: *** [Makefile:260: sak.o] Error 1
```

oh no

**Comment by Octachron** [comment]
Arg, I had missed the fact that we needed to backport the OCaml 5 definitions for `__has_builtin`. I would do that, remove the 4.14.3 package from this PR and send a separate PR with the ocaml 4.14.3 packages.

**Comment by MisterDA** [comment]
OpenSUSE Leap 15.6 is using GCC 7 which doesn't have `__has_builtin`. There is an unfortunate typo in `runtime/caml/misc.h` on 4.14.3, introduced in https://github.com/ocaml/ocaml/commit/b0a2614684a52acded784ec213f14ddfe085d146, which prevents the header from working with older GCC. After applying the following patch, OCaml 4.14.3 builds correctly.

```patch
diff --git a/runtime/caml/misc.h b/runtime/caml/misc.h
index 6fefe922ae..2e6c544065 100644
--- a/runtime/caml/misc.h
+++ b/runtime/caml/misc.h
@@ -260,7 +260,7 @@ CAMLnoreturn_end;
 #endif

 /* Branch prediction */
-#if __has_builtin(__builtin_expect) || defined(__GNUC__)
+#if Caml_has_builtin(__builtin_expect) || defined(__GNUC__)
 #define CAMLlikely(e)   __builtin_expect(!!(e), 1)
 #define CAMLunlikely(e) __builtin_expect(!!(e), 0)
 #else
 ```

**Comment by Octachron** [comment]
I was more thinking of using
```diff
diff --git a/runtime/caml/misc.h b/runtime/caml/misc.h
index 6fefe922ae..4d3684415f 100644
--- a/runtime/caml/misc.h
+++ b/runtime/caml/misc.h
@@ -29,6 +29,21 @@
 #include <stdlib.h>
 #include <stdarg.h>
 
+
+/* Detection of available C attributes and compiler extensions */
+
+#ifndef __has_c_attribute
+#define __has_c_attribute(x) 0
+#endif
+
+#ifndef __has_attribute
+#define __has_attribute(x) 0
+#endif
+
+#ifndef __has_builtin
+#define __has_builtin(x) 0
+#endif
+
 /* Deprecation warnings */
 
 #if defined(__GNUC__) || defined(__clang__)
@@ -253,11 +268,7 @@ CAMLnoreturn_end;
 
 /* Detection of available C built-in functions, the Clang way. */
 
-#ifdef __has_builtin
 #define Caml_has_builtin(x) __has_builtin(x)
-#else
-#define Caml_has_builtin(x) 0
-#endif
 
 /* Branch prediction */
 #if __has_builtin(__builtin_expect) || defined(__GNUC__)
```
in order to prevent future similar mistakes created by this minor difference between OCaml 4 and OCaml 5. 

Do you see a reason to prefer your version?

**Comment by Octachron** [comment]
Ok, let's use the minimal fix for now.

**Comment by Octachron** [comment]
Change of plans, I have updated directly the 4.14.3 packages and tag.

**Comment by MisterDA** [comment]
> Do you see a reason to prefer your version?

Apart from the diff being smaller… in the grand scheme of things I too like your version better, but mine is more adapted to the 4.14 branch: there is also a use of `Caml_has_builtin` in `runtime/misc.c` that your patch above misses (but a build would have caught it, I think).

**Comment by MisterDA** [comment]
Is this good to go? Do we care about the opam lint reports?
The other failures are that the CI script uses `--update-invariant` on opam 2.0 which doesn't have this flag, it's for a more recent version of opam.

**Comment by Octachron** [comment]
The linter warnings are just a sign that the compiler packages are not completely ordinary packages.
Maybe some of those warnings could be fixed, but this is probably not the right place.
 
Note that if I have the necessary rights to merge the PR, ideally I prefer to keep the package maintainer role and repository maintainer role separated. If this cause too much friction, we could decide that I should merge the compiler packages after a 12 hour or 24 hour delay?

**Comment by hannesm** [comment]
Thanks for the release. I'll merge since they look good (thanks for @MisterDA review), and I'm eager to have these fixed OCaml releases out in the wild.

**Comment by Octachron** [comment]
Thanks @hannesm !
