### PR TITLE
Constrain release to lwt <= 2.4.6.

### PR DESCRIPTION
**Pull request by yallop**
Release [doesn't build with the latest lwt](http://www.recoil.org/~avsm/opam-bulk/logs/local-debian-stable-ocaml-4.02.1/raw/release.html):

```
E: Cannot find findlib package lwt.syntax
E: Cannot find findlib package lwt.syntax (>= 2.4.0)
```

/cc @andrenth

### CODE REVIEW

**Comment by avsm** [comment]
Does this just need an explicit camlp4 dependency to get lwt.syntax?

**Comment by yallop** [comment]
Not in this case: there's apparently also an API change in lwt 2.4.7 that causes the release build to fail:

```
# File "lib/buffer/release_buffer.ml", line 37, characters 2-29:
# Error: Unbound value Lwt_bytes.blit_string_bytes
```

**Comment by andrenth** [comment]
Hi

Sorry for the delay replying to this. I've just pushed a fix to release's master branch so that it compiles with lwt 2.4.7 (I wish they wouldn't break their interfaces on point releases...). Before tagging a new version, should I add the camlp4 dependency on release itself? Shouldn't it be on the lwt.syntax package?

Cheers,
Andre

**Comment by yallop** [comment]
Camlp4 support is now optional in lwt: the `lwt.syntax` subpackage is only installed by OPAM if you have camlp4 installed.  If you need `lwt.syntax` then the best thing is to depend on both `lwt` and `camlp4`.
