### PR TITLE
ppx_tools_versioned.5.2: avoid installation thereof (leads to huge binaries), fixed in 5.2.1

### PR DESCRIPTION
**Pull request by hannesm**
would be happy to hear what @avsm @samoht and other think about this, my reasoning is that I'd like to avoid anyone from installing this package.  I'd be glad to remove the metadata completely instead of marking it as unavailable (as you prefer).

### CODE REVIEW

**Comment by avsm** [comment]
There appear to be some regressions with 5.2.1 that I haven't had time to look at yet :-/ Need to check those before pulling this package.

**Comment by mseri** [comment]
Please wait to merge this, otherwise the packages that depend on sedlex sill all be uninstallable

**Comment by samoht** [comment]
There's indeed a regression in 5.2.1:

```
#=== ERROR while installing sedlex.1.99.4 =====================================#
# opam-version 1.2.2
# os           linux
# command      make all
# path         /home/samoht/.opam/4.06.1/build/sedlex.1.99.4
# compiler     4.06.1
# exit-code    2
# env-file     /home/samoht/.opam/4.06.1/build/sedlex.1.99.4/sedlex-26967-be0162.env
# stdout-file  /home/samoht/.opam/4.06.1/build/sedlex.1.99.4/sedlex-26967-be0162.out
# stderr-file  /home/samoht/.opam/4.06.1/build/sedlex.1.99.4/sedlex-26967-be0162.err
### stdout ###
# [...]
# rm -rf ../../libdoc
# mkdir ../../libdoc
# ocamlfind ocamldoc -package gen -html sedlexing.mli -d ../../libdoc
# make[1]: Leaving directory '/home/samoht/.opam/4.06.1/build/sedlex.1.99.4/src/lib'
# (cd src/syntax && make all)
# make[1]: Entering directory '/home/samoht/.opam/4.06.1/build/sedlex.1.99.4/src/syntax'
# ocamlfind ocamlc -package ppx_tools_versioned.metaquot_405 -package ocaml-migrate-parsetree -linkall -w +A-4-9-42 -annot -a -o sedlex.cma sedlex_cset.mli sedlex_cset.ml unicode63.mli unicode63.ml sedlex.mli sedlex.ml ppx_sedlex.ml
# Makefile:18: recipe for target 'sedlex.cma' failed
# make[1]: Leaving directory '/home/samoht/.opam/4.06.1/build/sedlex.1.99.4/src/syntax'
# Makefile:13: recipe for target 'all' failed
### stderr ###
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/samoht/.opam/4.06.1/lib/ocaml, /home/samoht/.opam/4.06.1/lib/ocaml/compiler-libs
# File "ppx_sedlex.ml", line 11, characters 5-24:
# Error: Unbound module Ast_convenience_405
# make[1]: *** [sedlex.cma] Error 2
# make: *** [all] Error 2
```

this works fine with 5.1 and 5.2

**Comment by hannesm** [comment]
closing, this conflicts.  if anyone knows when we can get rid of ppx_tools_versioned 5.2, please open a new PR.
