### PR TITLE
Package jupyter.3.0.0

### PR DESCRIPTION
**Pull request by zhelih**
### `jupyter.3.0.0`
An OCaml kernel for Jupyter
This provides an OCaml REPL with a great user interface such as markdown/HTML documentation, LaTeX formula by MathJax, and image embedding.

---
* Homepage: https://akabe.github.io/ocaml-jupyter/
* Source repo: git+https://github.com/akabe/ocaml-jupyter.git
* Bug tracker: https://github.com/akabe/ocaml-jupyter/issues

---
:camel: Pull-request generated by opam-publish v2.7.1

### CODE REVIEW

**Review by jmid — COMMENTED** [review]
Thanks!

CI seems to fail consistently on ocaml 5.4 workflows:
https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/342beafb93220805219beffb91ce6d181f16f7fd/variant/compilers,5.4,jupyter.3.0.0
```
#=== ERROR while compiling jupyter.3.0.0 ======================================#
# context              2.5.0 | linux/x86_64 | ocaml-base-compiler.5.4.0 | pinned(https://github.com/akabe/ocaml-jupyter/archive/refs/tags/v3.0.0.tar.gz)
# path                 ~/.opam/5.4/.opam-switch/build/jupyter.3.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p jupyter -j 255
# exit-code            1
# env-file             ~/.opam/log/jupyter-7-b88be6.env
# output-file          ~/.opam/log/jupyter-7-b88be6.out
### output ###
# (cd _build/default && /home/opam/.opam/5.4/bin/ocamlc.opt -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58-66-70 -safe-string -strict-sequence -strict-formats -short-paths -g -bin-annot -bin-annot-occurrences -I src/repl/.jupyter_repl.objs/byte -I /home/opam/.opam/5.4/lib/bytes -I /home/opam/.opam/5.4/lib/logs -I /home/opam/.opam/5.4/lib/logs/lwt -I /home/opam/.opam/5.4/lib/lwt -I /home/opam/.opam/5.4/lib/lwt/unix -I /home/opam/.opam/5.4/lib/ocaml/compiler-libs -I /home/opam/.opam/5.4/lib/ocaml/str -I /home/opam/.opam/5.4/lib/ocaml/threads -I /home/opam/.opam/5.4/lib/ocaml/unix -I /home/opam/.opam/5.4/lib/ocplib-endian -I /home/opam/.opam/5.4/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.4/lib/ppx_yojson_conv_lib -I /home/opam/.opam/5.4/lib/uuidm -I /home/opam/.opam/5.4/lib/yojson -I src/core/.jupyter.objs/byte -I src/log/.jupyter_log.objs/byte -cmi-file src/repl/.jupyter_repl.objs/byte/jupyter_repl__Lwt_async_rewrite.cmi -no-alias-deps -open Jupyter_repl__ -o src/repl/.jupyter_repl.objs/byte/jupyter_repl__Lwt_async_rewrite.cmo -c -impl src/repl/lwt_async_rewrite.pp.ml)
# File "lwt_async_rewrite.cppo.ml", line 28, characters 45-72:
# Error: This expression should not be a constructor, the expected type is
#        Longident.t Location.loc
# (cd _build/default && /home/opam/.opam/5.4/bin/ocamlc.opt -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58-66-70 -safe-string -strict-sequence -strict-formats -short-paths -g -bin-annot -bin-annot-occurrences -I src/repl/.jupyter_repl.objs/byte -I /home/opam/.opam/5.4/lib/bytes -I /home/opam/.opam/5.4/lib/logs -I /home/opam/.opam/5.4/lib/logs/lwt -I /home/opam/.opam/5.4/lib/lwt -I /home/opam/.opam/5.4/lib/lwt/unix -I /home/opam/.opam/5.4/lib/ocaml/compiler-libs -I /home/opam/.opam/5.4/lib/ocaml/str -I /home/opam/.opam/5.4/lib/ocaml/threads -I /home/opam/.opam/5.4/lib/ocaml/unix -I /home/opam/.opam/5.4/lib/ocplib-endian -I /home/opam/.opam/5.4/lib/ocplib-endian/bigstring -I /home/opam/.opam/5.4/lib/ppx_yojson_conv_lib -I /home/opam/.opam/5.4/lib/uuidm -I /home/opam/.opam/5.4/lib/yojson -I src/core/.jupyter.objs/byte -I src/log/.jupyter_log.objs/byte -cmi-file src/repl/.jupyter_repl.objs/byte/jupyter_repl__Caml_args.cmi -no-alias-deps -open Jupyter_repl__ -o src/repl/.jupyter_repl.objs/byte/jupyter_repl__Caml_args.cmo -c -impl src/repl/caml_args.pp.ml)
# File "caml_args.cppo.ml", line 131, characters 28-55:
# Error: Unbound value Clflags.transparent_modules
```

**Comment by zhelih** [comment]
Yes, I will work on the 5.4.0 support and re-release, thank you.

**Comment by zhelih** [comment]
Superseded by #29142
