### PR TITLE
Add pyml.20161224

### PR DESCRIPTION
**Pull request by thierry-martinez**

### CODE REVIEW

**Comment by samoht** [comment]
Can you add a version constraint for `ocaml-version >= "4.01.0"? It's failing on older versions with:

```
#=== ERROR while installing pyml.20161220 =====================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/4.00.1/build/pyml.20161220
# compiler     4.00.1
# exit-code    2
# env-file     /home/travis/.opam/4.00.1/build/pyml.20161220/pyml-16405-2c871f.env
# stdout-file  /home/travis/.opam/4.00.1/build/pyml.20161220/pyml-16405-2c871f.out
# stderr-file  /home/travis/.opam/4.00.1/build/pyml.20161220/pyml-16405-2c871f.err
### stdout ###
# [...]
# ocamlfind ocamlc  -c pyml_arch.mli -o pyml_arch.cmi
# ocamlfind ocamlc -i pywrappers.ml >pywrappers.mli
# ocamlfind ocamldep pyml_compat.ml pyml_arch.ml pytypes.ml pywrappers.ml py.ml pycaml.ml pyml_compat.mli pyml_arch.mli pytypes.mli pywrappers.mli py.mli pycaml.mli pyml_tests.ml >.depend
# ocamlfind ocamlc  -c pyml_compat.ml -o pyml_compat.cmo
# ocamlfind ocamlc  -c pyml_arch.ml -o pyml_arch.cmo
# ocamlfind ocamlc  -c pytypes.ml -o pytypes.cmo
# ocamlfind ocamlc  -c pywrappers.mli -o pywrappers.cmi
# ocamlfind ocamlc  -c pywrappers.ml -o pywrappers.cmo
# ocamlfind ocamlc  -c py.mli -o py.cmi
# ocamlfind ocamlc  -c py.ml -o py.cmo
### stderr ###
# File "py.ml", line 280, characters 11-20:
# Error: Unbound value Sys.win32
# make: *** [py.cmo] Error 2
```

**Comment by thierry-martinez** [comment]
@samoht Oops, it was supposed to work with OCaml 3.12 too! It should be fixed now, thank you.

**Comment by samoht** [comment]
All working now, thanks!
