### PR TITLE
opam fix for treeprint

### PR DESCRIPTION
**Pull request by camlspotter**

### CODE REVIEW

**Comment by camlspotter** [comment]
Installation failure of ppx_meta_conv 2.3.0

```
File "ppx_meta_conv.ml", line 1097, characters 4-171:
# Error: Some record fields are undefined: module_type_decl_str
#        module_type_decl_sig
# *** omake: targets were not rebuilt because of errors:
#    src/ppx_meta_conv.cmo
#       depends on: src/ppx_meta_conv.ml
```

**Comment by avsm** [comment]
Looks like ppx_meta_conv also doesnt build on 4.02.3:

```
#=== ERROR while compiling ppx_meta_conv.2.2.0 ================================#
# command              ocaml setup.ml -build
# path                 /home/opam/.opam/ocaml-base-compiler.4.02.3/.opam-switch/build/ppx_meta_conv.2.2.0
# exit-code            1
# env-file             /home/opam/.opam/log/ppx_meta_conv-31-462d2b.env
# output-file          /home/opam/.opam/log/ppx_meta_conv-31-462d2b.out
### output ###
# [...]
# *** omake: 90/323 targets are up to date
# *** omake: failed (1.03 sec, 11/11 scans, 18/30 rules, 60/217 digests)
# *** omake: targets were not rebuilt because of errors:
#    src/ppx_meta_conv.cmi
#       depends on: src/ppx_meta_conv.ml
#    src/ppx_meta_conv.cmo
#       depends on: src/ppx_meta_conv.ml
#    src/ppx_meta_conv.cmx
#       depends on: src/ppx_meta_conv.ml
#    src/ppx_meta_conv.o
#       depends on: src/ppx_meta_conv.ml
# E: Failure("Command 'sh -c \"cp OMakeroot.in OMakeroot; omake PREFIX=\"' terminated with error code 2")

```

**Comment by camlspotter** [comment]
We need the same constraint for ppx_meta_conv.2.2.0

**Comment by camlspotter** [comment]
travis-ci failure for OCAML_VERSION=4.02 OPAM_VERSION=1.2.0 but it is at the environment init phase.  Could someone restart it ?

**Comment by avsm** [comment]
restarted

**Comment by yallop** [comment]
Thanks!
