### PR TITLE
ppx_deriving: update bounds on OCaml version

### PR DESCRIPTION
**Pull request by damiendoligez**
`ppx_deriving` does not work with 4.05.0+beta3 because the AST changed. IIUC `ppx_deriving` will have to be adapted, possibly with the help of `ocaml-migrate-parsetree`.

cc @whitequark

### CODE REVIEW

**Comment by avsm** [comment]
lots of fails here on the nature of

```
# $ (cd _build/default && /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base/caml -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base/shadow_stdlib -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml -I /home/opam/.opam/ocaml-base-compiler.4.03.0/[...]
# File "src/type_conv.ml", line 515, characters 6-36:
# Error: Unbound value Ppx_deriving.add_register_hook
```

**Comment by avsm** [comment]
fixed transmission-rpc revdep failure in #8930

**Comment by avsm** [comment]
and ppx_json_types revdeps failure in #8931

**Comment by avsm** [comment]
prob-cache-1.1 failure fixed in #8932

**Comment by avsm** [comment]
The add_register_hook failures are all fixed by https://github.com/ocaml/opam-repository/pull/8933 hopefully

**Comment by damiendoligez** [comment]
>lots of fails here on the nature of
```
# $ (cd _build/default && /home/opam/.opam/ocaml-base-compiler.4.03.0/bin/ocamlc.opt -w -40 -g -bin-annot -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base/caml -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/base/shadow_stdlib -I /home/opam/.opam/ocaml-base-compiler.4.03.0/lib/ocaml -I /home/opam/.opam/ocaml-base-compiler.4.03.0/[...]
# File "src/type_conv.ml", line 515, characters 6-36:
# Error: Unbound value Ppx_deriving.add_register_hook
```

AFAICT this is because `ppx_type_conv.v0.9.0` is incompatible with `ppx_deriving.4.0`, so the `conflicts` field should be updated to 4.1.

**Comment by avsm** [comment]
yep -- just to confirm this is fixed in #8933, so i merged this
