### PR TITLE
[new release] mirage (2 packages) (4.5.1)

### PR DESCRIPTION
**Pull request by hannesm**
The MirageOS library operating system

- Project page: <a href="https://github.com/mirage/mirage">https://github.com/mirage/mirage</a>
- Documentation: <a href="https://mirage.github.io/mirage/">https://mirage.github.io/mirage/</a>

##### CHANGES:

- BREAKING: remove `~name` parameter from Mirage.Runtime_args.create
  (mirage/mirage#1541 @samoht, fixes mirage/mirage#1532)
- BREAKING: remove `~name` parameter from Mirage.runtime_arg, and use a
  string (instead of a format string) as third parameter (mirage/mirage#1541 @samoht)
- constrain the `start` function to `unit Lwt.t`. Previously, there was no
  restrictions, and lots of time was spent in debugging when a unikernel
  resulted in `unit Lwt.t Lwt.t` (@Julow mirage/mirage#1524)
- revise man page sections and ordering: ARGUMENTS, OPTIONAL, NETWORK OPTIONS,
  DISK OPTIONS, LOG AND MONITORING OPTIONS, OCAML RUNTIME OPTIONS. Previously,
  the ARGUMENTS and OPTIONS were put later, and were hard to find. These are
  the sections where unikernel-specific arguments are put by default
  (mirage/mirage#1531 @hannesm @reynir)
- add --net=host and --net=ocaml to reduce confusion. --net=host uses the
  TCP/IP socket stack, --net=ocaml the OCaml network stack (mirage/mirage#1525 @hannesm)
- quote Runtime_arg.call (mirage/mirage#1522 @Julow)
- documentation fixes (inline examples @Julow mirage/mirage#1523, @hannesm mirage/mirage#1537 (fixes
  mirage/mirage#1512 reported by @reynir), Runtime_args.create mirage/mirage#1541 @samoht)
- fix the build instructions of the generated opam file: since 4.5.0
  `mirage build` is no longer available, use `make "build"` (mirage/mirage#1527 @hannesm)
- add RELEASE.md, a guide on how to cut a mirage release (mirage/mirage#1519 @samoht)
- allow git 3.16 (mirage/mirage#1536 @hannesm)
- use mirage-bootvar (using dune variant) instead of parse-argv and
  mirage-bootvar-xen, mirage-bootvar-solo5, mirage-bootvar-unix
  (mirage/mirage#1533 @hannesm)
- BUGFIX: reset the lexer location before applying functors in generated code
  (mirage/mirage#1539 @samoht, fixes mirage/mirage#1520 @hannesm)
- BUGFIX: fix off-by-one locations for mirage/main.ml (mirage/mirage#1540 @samoht, fixes
  mirage/mirage#1528 @hannesm)

### CODE REVIEW

**Comment by hannesm** [comment]
errors in the expect tests with OCaml 5.1 (works fine with 4.14)

```
# --- a/_build/.sandbox/c7441d067438e40b9ac24c36151613c8/default/test/functoria/e2e/errors.t
# +++ b/_build/.sandbox/c7441d067438e40b9ac24c36151613c8/default/test/functoria/e2e/errors.t.corrected
# @@ -4,8 +4,8 @@ of a device's connect function:
#    $ ./test.exe configure -f errors/in_device.ml
#    $ dune build
#    File "errors/config.ml", line 6, characters 2-26:
# -  Error: Unbound value Unikernel_make__4.start'
# -  Hint: Did you mean start?
# +  Error: Unbound value "Unikernel_make__4.start'"
# +  Hint: Did you mean "start"?
#    [1]
#    $ ./test.exe clean -f errors/in_device.ml
```

Any idea how to deal with this? Something added `"` in the OCaml 5.1 error message. I've no idea whether the expect tests should care about that (and if there's some conditional behavour depending on the OCaml version?).

What I think is that we can disable tests for ocaml > 5.

Maybe @samoht has an idea?

**Comment by hannesm** [comment]
CI errors are unrelated, good to merge!

**Comment by dinosaure** [comment]
Thanks!
