### ISSUE TITLE
ocamlot triage 20130830 mainly for Linux 4.00.1 and some 4.1

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-repository#1029]
Triage results to keep track of issues before fixing them all.  Note that the link URLs will break later (we need a permalink mechanism for these -- I'll edit the issue with the version of ocamlot-state required to reconstruct these links later). 
- [x] why3 broken because of coq pl2 (transient - coq server was down)
- [ ] fftw fails with system compiler, 4.00.1 system --  (can be fixed in opam 1.1 with new `available` field, see OCamlPro/opam#789)
- [x] ocaml-lua cannot find topfind on both 4.00.1 and 4.01 - failure is only on `system` compiler
- [x] websocket.0.6 needs an newer version of cohttp  (vbmithr/ocaml-websocket#9)
- [x] xen-block-driver.0.2.2 has a dependency on mirage.0.9.4 (old), which fails due a mismatch on xenstore interface change.  (mirage/ocaml-xen-block-driver#2)
- [x] opam2web fails to build with a linking error  (OCamlPro/opam2web#45)
- [x] eliom is trying to create a /tmp/log for some reason - https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/2373 (fixed upstream in ocsigen/eliom#2)
- [x] sexplib.7.0.5 doesnt work with Toploop on 4 -- compiler constraint on 3.12.1 if superseded by Core version? https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/5637 (fixed in 94d667fd487eca8b54c293a452e48ef87e2b62e1 and ocamlot bug filed in ocamllabs/ocamlot#42)
- [ ] spotinstall - yet another omake error https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/2901
- [x] batteries.2.1.0 fails to build with O_CLOEXEC failure (opened as #1031)
- [x] libfgs has malformed log file on configure, so needs an oasis setup on ocaml4+
- [ ] planck.2.1.1 fails due to unbound module -- missing dep? https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/489
- [ ] mirage-www fails due to mirari unix problem
## 4.01.00 specific breakage
- [x] zipperposition.0.2 broken with 4.01 due to signature change but works on 4.00.1 (c-cube/zipperposition#1)
- [x] mascot.1.0 fails with 4.1 (maintainer emailed, can add constraint to 4.0)
- [x] treeprint is ocaml 4.00.1 only due to transitive dependency on meta_conv which is restricted like that.
- [x] mlorg doesnt work with 4.01 since it has multiple duplicate method definitions in a single object
- [x] ocamleditor requires 4.00.[01] and fails on newer versions.
- [x] rml.1.08.06 fails with an ocamlbuild plugin error only in 4.01.0 (have mailed devel list)
- [x] ocamlspot has a compiler dependency that includes 4.1, but it only works 4.00.0 and 4.00.1 (mailed maintainer)
- [x] treeprint.1.0.2 is missing a dep on ocaml_conv -- omake error https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/2985
- [x] pa_do fails with camlp4 type mismatch, need patch for 4.1 version
- [x] pomap fails in 4.01 with incorrect signature for `Set` (needs new `find` function also)
- [ ] ocamlgraph fails on 4.01 due to warnings-as-errors from new warnings (backtracking/ocamlgraph#5)
- [ ] spotlib_js fails due to warnings-as-errors from 4.01 specific warnings
- [ ] ocaml-indent.1.1.0 fails in 4.01 due to compiler-libs type error
- [ ] quickcheck has warnings-as-errors failure due to new operator in Pervasives (open statement shadows |>)
- [ ] opa-base has warnings-as-errors (deprecated feature `||`)
- [ ] lablgtk-extras has warnings-as-errors (deprecated feature `||`)
- [ ] plasma has warnings-as-errors (deprecated feature `||`)
- [ ] biocaml.0.2.0 depends on an older Core that doesnt have the CLOEXEC patch
- [ ] mesh.0.7.6 has Camlp4 `Delete.Rule_not_found` compile type error
- [x] pxp had too tight a dep on ocamlnet=3.6.0 (which doesnt work with 4.01). Possibly due to some change in how Netstring_pcre works.
## Missing deps
- [x] Benchmark 1.2 needs a depend on pcre https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/2889
- [x] cfstream is missing a dependency on core https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/2769
- [x] odisco is missing a dependency on zip
- [x] ibx missing a dependency on textutils 
- [x] vhdformat missing a dep on ounit
- [x] flow.0.2 was picking up an old version of Core without CLOEXEC, so added firmer constraint (not really this packages fault)
- [x] xenctrl is missing dep on cmdliner
- [x] extprot is missing dep on omake
- [x] xenctrl is missing dep on cstruct
## Portability
- [x] facile uses `make` directly instead of `$(MAKE)` so fails on BSD 
- [ ] numerix uses `make` directly too in OCamlPro/opam-repository#797
- [ ] crypt.1.2 fails on freebsd due to missing `-lcrypt` - missing reference to `crypt` symbol
- [ ] odisco tests exceed 32-bit integer literal limit (discoproject/odisco#3)
- [x] qmp tests exceed 32-bit integer literal limit (xapi-project/ocaml-qmp#3)
- [x] lilis.0.1.3 missing dep on menhir
- [ ] jenga dies on i386 due to Buffer size limit (janestreet/jenga#3) -- ocamlplugin is causing this
- [ ] core_extended uses x86-specific rtdsc timer so doesnt work on arm/macppc (janestreet/core_extended#3)
- [ ] posix_resource fails on OpenBSD/macppc with `'RLIMIT_AS' undeclared`
- [ ] yajl fails on OpenBSD with missing cmake and some grep unportability
- [ ] Core.109.40.00 IOBuf stubs fail to build on OpenBSD (janestreet/core#26)
- [ ] json-wheel fails to link on OpenBSD due to missing pthread/sem library symbols
- [ ] numerix doesnt have a macppc/powerpc.S and so fails on that arch
- [ ] Core_extended fails to build on FreeBSD 9.1 due to missing quota.h
## Ext deps
- [ ] libvhd has an extdep
- [ ] opus has an extdep on libopus >= 1.0.0
- [ ] ocsfml needs extdep on boost https://ocamlot.recoil.org/github/OCamlPro/opam-repository/task/525
- [ ] sodium has an extdep on libsodium
- [ ] ocaml-usb has an extep
