### PR TITLE
[new release] re (1.10.0)

### PR DESCRIPTION
**Pull request by rgrinberg**
RE is a regular expression library for OCaml

- Project page: <a href="https://github.com/ocaml/ocaml-re">https://github.com/ocaml/ocaml-re</a>

##### CHANGES:

* Add the `[:alpha:]` character class in `Re.Perl` (ocaml/ocaml-re#169)
* Double asterisk (`**`) in `Re.Glob` (ocaml/ocaml-re#172)
  Like `*` but also match `/` characters when `pathname` is set.
* Double asterisk should match 0 or more directories unless in trailing
  position. (ocaml/ocaml-re#192, fixes ocaml/ocaml-re#185)

### CODE REVIEW

**Comment by mseri** [comment]
The failures seem to be independent

**Comment by kit-ty-kate** [comment]
> The failures seem to be independent

These ones don't seem to be:
```
# File "src/tyre.ml", line 332, characters 19-29:
# 332 |     Seq.map aux @@ Re.all_seq ~pos ~len re original
#                          ^^^^^^^^^^
# Error: Unbound value Re.all_seq
# Hint: Did you mean all_gen?
```
I double checked and it worked with the previous version of `re` (1.9.0). However I can't find the commit that removed it or any mention of it in the changelog, which i find very weird. @rgrinberg was this meant to happen?

**Comment by rgrinberg** [comment]
Good catch. This was indeed an accidental regression. I released 1.10.1 with the fixe.
