### PR TITLE
Package jupyter-kernel.0.8

### PR DESCRIPTION
**Pull request by c-cube**
### `jupyter-kernel.0.8`
Library to write jupyter kernels (interactive notebooks)

---
* Homepage: https://github.com/ocaml-jupyter/jupyter-kernel
* Source repo: git+https://github.com/ocaml-jupyter/jupyter-kernel.git
* Bug tracker: https://github.com/ocaml-jupyter/jupyter-kernel/issues

---
:camel: Pull-request generated by opam-publish v2.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Could you add the appropriate lower-bound constraints so that these modules and functions are available?
```
#=== ERROR while compiling jupyter-kernel.0.8 =================================#
# context              2.1.1 | linux/x86_64 | ocaml-base-compiler.4.08.1 | pinned(https://github.com/ocaml-jupyter/jupyter-kernel/archive/v0.8.tar.gz)
# path                 ~/.opam/4.08/.opam-switch/build/jupyter-kernel.0.8
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build @install -p jupyter-kernel -j 31
# exit-code            1
# env-file             ~/.opam/log/jupyter-kernel-10484-f82a12.env
# output-file          ~/.opam/log/jupyter-kernel-10484-f82a12.out
### output ###
#       ocamlc src/.jupyter_kernel.objs/jupyter_kernel__Message.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -safe-string -warn-error -a+8 -g -bin-annot -I src/.jupyter_kernel.objs -I src/.jupyter_kernel.objs/.private -I /home/opam/.opam/4.08/lib/atd -I /home/opam/.opam/4.08/lib/atdgen -I /home/opam/.opam/4.08/lib/base -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/base/shadow_stdlib -I /home/opam/.opam/4.08/lib/biniou -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/digestif -I /home/opam/.opam/4.08/lib/easy-format -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lwt -I /home/opam/.opam/4.08/lib/lwt/unix -I /home/opam/.opam/4.08/lib/mmap -I /home/opam/.opam/4.08/lib/ocaml/threads -I /home/opam/.opam/4.08/lib/ptime -I /home/opam/.opam/4.08/lib/ptime/os -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/seq -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdint -I /home/opam/.opam/4.08/lib/uchar -I /home/opam/.opam/4.08/lib/uuidm -I /home/opam/.opam/4.08/lib/uutf -I /home/opam/.opam/4.08/lib/yojson -I /home/opam/.opam/4.08/lib/zmq -I /home/opam/.opam/4.08/lib/zmq-lwt -I /home/opam/.opam/4.08/lib/zmq/deferred -intf-suffix .ml -no-alias-deps -open Jupyter_kernel -o src/.jupyter_kernel.objs/jupyter_kernel__Message.cmo -c -impl src/Message.ml)
# File "src/Message.ml", line 217, characters 6-21:
# 217 |       Digestif.SHA256.(hmaci_string ~key:k c |> to_hex)
#             ^^^^^^^^^^^^^^^
# Error: Unbound module Digestif.SHA256
#       ocamlc src/.jupyter_kernel.objs/jupyter_kernel__Protocol_j.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlc.opt -w -40 -safe-string -warn-error -a+8 -g -bin-annot -I src/.jupyter_kernel.objs -I src/.jupyter_kernel.objs/.private -I /home/opam/.opam/4.08/lib/atd -I /home/opam/.opam/4.08/lib/atdgen -I /home/opam/.opam/4.08/lib/base -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/base/shadow_stdlib -I /home/opam/.opam/4.08/lib/biniou -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/digestif -I /home/opam/.opam/4.08/lib/easy-format -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lwt -I /home/opam/.opam/4.08/lib/lwt/unix -I /home/opam/.opam/4.08/lib/mmap -I /home/opam/.opam/4.08/lib/ocaml/threads -I /home/opam/.opam/4.08/lib/ptime -I /home/opam/.opam/4.08/lib/ptime/os -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/seq -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdint -I /home/opam/.opam/4.08/lib/uchar -I /home/opam/.opam/4.08/lib/uuidm -I /home/opam/.opam/4.08/lib/uutf -I /home/opam/.opam/4.08/lib/yojson -I /home/opam/.opam/4.08/lib/zmq -I /home/opam/.opam/4.08/lib/zmq-lwt -I /home/opam/.opam/4.08/lib/zmq/deferred -intf-suffix .ml -no-alias-deps -open Jupyter_kernel -o src/.jupyter_kernel.objs/jupyter_kernel__Protocol_j.cmo -c -impl src/Protocol_j.ml)
# File "src/Protocol_j.ml", line 172, characters 2-21:
# 172 |   Yojson.Safe.write_t
#         ^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Yojson.Safe.write_t
# Hint: Did you mean write_int?
#     ocamlopt src/.jupyter_kernel.objs/jupyter_kernel__Protocol_j.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.08/bin/ocamlopt.opt -w -40 -safe-string -warn-error -a+8 -g -I src/.jupyter_kernel.objs -I src/.jupyter_kernel.objs/.private -I /home/opam/.opam/4.08/lib/atd -I /home/opam/.opam/4.08/lib/atdgen -I /home/opam/.opam/4.08/lib/base -I /home/opam/.opam/4.08/lib/base/caml -I /home/opam/.opam/4.08/lib/base/shadow_stdlib -I /home/opam/.opam/4.08/lib/biniou -I /home/opam/.opam/4.08/lib/bytes -I /home/opam/.opam/4.08/lib/digestif -I /home/opam/.opam/4.08/lib/easy-format -I /home/opam/.opam/4.08/lib/logs -I /home/opam/.opam/4.08/lib/lwt -I /home/opam/.opam/4.08/lib/lwt/unix -I /home/opam/.opam/4.08/lib/mmap -I /home/opam/.opam/4.08/lib/ocaml/threads -I /home/opam/.opam/4.08/lib/ptime -I /home/opam/.opam/4.08/lib/ptime/os -I /home/opam/.opam/4.08/lib/result -I /home/opam/.opam/4.08/lib/seq -I /home/opam/.opam/4.08/lib/sexplib0 -I /home/opam/.opam/4.08/lib/stdint -I /home/opam/.opam/4.08/lib/uchar -I /home/opam/.opam/4.08/lib/uuidm -I /home/opam/.opam/4.08/lib/uutf -I /home/opam/.opam/4.08/lib/yojson -I /home/opam/.opam/4.08/lib/zmq -I /home/opam/.opam/4.08/lib/zmq-lwt -I /home/opam/.opam/4.08/lib/zmq/deferred -intf-suffix .ml -no-alias-deps -open Jupyter_kernel -o src/.jupyter_kernel.objs/jupyter_kernel__Protocol_j.cmx -c -impl src/Protocol_j.ml)
# File "src/Protocol_j.ml", line 172, characters 2-21:
# 172 |   Yojson.Safe.write_t
#         ^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Yojson.Safe.write_t
# Hint: Did you mean write_int?
```

**Comment by c-cube** [comment]
- for digestif, ok (is 1.1 the highest version that fails?)
- for the other one, I don't understand why it fails. I can see in 2.0.1 that it requires `yojson 1.7`, which seems correct. My code doesn't need more than yojson 1.6, so it should all work anyway?

**Comment by kit-ty-kate** [comment]
`write_t` doesn’t seem to exist before 1.7.0: https://github.com/ocaml-community/yojson/compare/1.6.0...1.7.0#diff-103acd1852db5172d96a8e32c81e15ef6193ca221bf62e00deda2c306e9dcda5R95

**Comment by kit-ty-kate** [comment]
oh those files are autogenerated! Then it’s a bug in the atdgen package definition (in this case it used 1.9.1). I’ll have a look

**Comment by c-cube** [comment]
yes exactly!

**Comment by kit-ty-kate** [comment]
@c-cube Actually atdgen has nothing to do with it. I was able to make it compile with yojson 1.6.0 if i change `t="t"` to `t="json"` in https://github.com/ocaml-jupyter/jupyter-kernel/blob/9a016a37faeafb426994158f2582130aa51f18c2/src/Protocol.atd

So `"yojson" {>= "1.7.0"}` is the appropriate fix I belive.

**Comment by kit-ty-kate** [comment]
The `license` field is also missing from the package and I couldn’t find the license file from the source code. Could you add it?

**Comment by kit-ty-kate** [comment]
All good now. There is just the missing license field to add and it’s all good.

**Comment by c-cube** [comment]
`t = "json"` will trigger deprecation warnings in later versions of yojson, which is why I moved to yojson 1.6. The fix is still to fix the faulty version of atdgen imho.

**Comment by kit-ty-kate** [comment]
> `t = "json"` will trigger deprecation warnings in later versions of yojson, which is why I moved to yojson 1.6. The fix is still to fix the faulty version of atdgen imho.

the atdgen code basically does `Yojson.Safe.write_<type>` so the problem is simply redirected to the user in this case. Restricting atdgen wouldn’t be the correct fix here IMO

**Comment by c-cube** [comment]
My point is that if atdgen generates code that requires yojson 1.7, it should be responsible for enforcing the bounds!

**Comment by kit-ty-kate** [comment]
Thanks!
