### ISSUE TITLE
planck.2.1.1 fails to build with 4.00.1 4.01.0 and 4.02.0+trunk

### ISSUE THREAD

**Issue by ygrek** [ocaml/opam-repository#2150]
Error is : 

```
### stderr ###
# ...[truncated]
# *** omake: warning: stdout is not a tty, disabling the progress bar
#    (use --progress to override).
# File "elem.ml", line 15, characters 10-32:
# Error: Unbound module Mtypes.Make_comparable
# *** omake: targets were not rebuilt because of errors:
#    lib/elem.cmx
#       depends on: lib/elem.ml
#    lib/elem.o
#       depends on: lib/elem.ml
# E: Failure("Command 'cp OMakeroot.in OMakeroot; PREFIX=/home/ygrek/.opam/4.02.0+trunk omake' terminated with error code 2")
```
