### PR TITLE
Package uritemplate.0.0.1

### PR DESCRIPTION
**Pull request by CorinChappy**
### `uritemplate.0.0.1`
OCaml implementation of URI templates (RFC6570)

---
* Homepage: https://github.com/CorinChappy/uritemplate-ocaml
* Source repo: git+https://https://github.com/CorinChappy/uritemplate-ocaml.git
* Bug tracker: https://github.com/CorinChappy/uritemplate-ocaml/issues

---
:camel: Pull-request generated by opam-publish v2.0.0

### CODE REVIEW

**Comment by mseri** [comment]
It does not compile on ocaml 4.02-4.04:
```

#=== ERROR while compiling uritemplate.0.0.1 ==================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.03.0 | pinned(https://github.com/CorinChappy/uritemplate-ocaml/archive/0.0.1.tar.gz)
# path                 ~/.opam/4.03/.opam-switch/build/uritemplate.0.0.1
# command              ~/.opam/4.03/bin/dune build -p uritemplate -j 71
# exit-code            1
# env-file             ~/.opam/log/uritemplate-20-475613.env
# output-file          ~/.opam/log/uritemplate-20-475613.out
### output ###
#       ocamlc src/.uritemplate.objs/byte/uritemplate.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.uritemplate.objs/byte -intf-suffix .ml -no-alias-deps -o src/.uritemplate.objs/byte/uritemplate.cmo -c -impl src/uritemplate.ml)
# File "src/uritemplate.ml", line 65, characters 8-22:
# Error: Unbound value List.assoc_opt
#     ocamlopt src/.uritemplate.objs/native/uritemplate.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -I src/.uritemplate.objs/byte -I src/.uritemplate.objs/native -intf-suffix .ml -no-alias-deps -o src/.uritemplate.objs/native/uritemplate.cmx -c -impl src/uritemplate.ml)
# File "src/uritemplate.ml", line 65, characters 8-22:
# Error: Unbound value List.assoc_opt

-       ocamlc src/.uritemplate.objs/byte/uritemplate.{cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/4.03/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.uritemplate.objs/byte -intf-suffix .ml -no-alias-deps -o src/.uritemplate.objs/byte/uritemplate.cmo -c -impl src/uritemplate.ml)
- File "src/uritemplate.ml", line 65, characters 8-22:
- Error: Unbound value List.assoc_opt
-     ocamlopt src/.uritemplate.objs/native/uritemplate.{cmx,o} (exit 2)
- (cd _build/default && /home/opam/.opam/4.03/bin/ocamlopt.opt -w -40 -g -I src/.uritemplate.objs/byte -I src/.uritemplate.objs/native -intf-suffix .ml -no-alias-deps -o src/.uritemplate.objs/native/uritemplate.cmx -c -impl src/uritemplate.ml)
- File "src/uritemplate.ml", line 65, characters 8-22:
- Error: Unbound value List.assoc_opt
```

A fast way to fix it is to require `stdcompat >= 5`, and prefix with the relevant module.

**Comment by CorinChappy** [comment]
Thanks @mseri, I noticed the error after submitting but didn't have time to fix it!

Should I update the tag in my repository and reuse this PR or submit a new one? This is my first submission so not sure of the process

**Comment by mseri** [comment]
As you prefer. This has not yet been released, feel free to update the tag (and the hash in the opam files) and reuse this PR

**Comment by CorinChappy** [comment]
I had a travis failure because I had String.equal (from 4.03.0) in my tests. I've removed it now, so everything should pass in this build

**Comment by mseri** [comment]
Looks good, thanks
