### PR TITLE
linenoise.1.0.0 - via opam-publish

### PR DESCRIPTION
**Pull request by fxfactorial**
Simple readline like functionality with nice hints feature.

These are self contained OCaml bindings to linenoise,
no system libraries needed at all.

Here's a simple program:
```ocaml
let rec user_input prompt cb =
  match LNoise.linenoise prompt with
  | None -> ()
  | Some v ->
    cb v;
    user_input prompt cb

let () =
  LNoise.set_hints_callback (fun line ->
      if line <> "git remote add " then None
      else Some (" <this is the remote name> <this is the remote URL>",
                 LNoise.Yellow,
                 true)
    );
  LNoise.history_load ~filename:"history.txt" |> ignore;
  LNoise.history_set ~max_length:100 |> ignore;
  LNoise.set_completion_callback begin fun line_so_far ln_completions ->
    if line_so_far <> "" && line_so_far.[0] = 'h' then
      ["Hey"; "Howard"; "Hughes";"Hocus"]
      |> List.iter (LNoise.add_completion ln_completions);
  end;
  ["These are OCaml bindings to linenoise";
   "get tab completion with <TAB>, type h then hit <TAB>";
   "type quit to exit gracefully";
   "By Edgar Aroutiounian\n"]
  |> List.iter print_endline;
  (fun from_user ->
     if from_user = "quit" then exit 0;
     LNoise.history_add from_user |> ignore;
     LNoise.history_save ~filename:"history.txt" |> ignore;
     Printf.sprintf "Got: %s" from_user |> print_endline
  )
  |> user_input "test_program> "
```

and compile with:
$ ocamlfind ocamlopt ex.ml -package linenoise -linkpkg -o T

Check out this gif: 

https://github.com/fxfactorial/ocaml-linenoise/blob/master/example.gif

---
* Homepage: https://github.com/fxfactorial/ocaml-linenoise
* Source repo: https://github.com/fxfactorial/ocaml-linenoise.git
* Bug tracker: https://github.com/fxfactorial/ocaml-linenoise/issues

---

Pull-request generated by opam-publish v0.3.2

### CODE REVIEW

**Comment by fxfactorial** [comment]
@yallop @dsheets why are OCaml packages being built against an unreleased compiler?

**Comment by yallop** [comment]
The aim is to have things working as far as possible with 4.04 by the time it's is released.  Building everything against 4.04 now helps to find bugs in the compiler and compatibility problems in packages.

**Comment by fxfactorial** [comment]
@yallop so why is the 4.04 failing but others are fine? Does 4.04 run with stricter warnings?

**Comment by yallop** [comment]
I'm not sure offhand.  I'll look into it shortly, unless someone beats me to it.

**Comment by yallop** [comment]
@fxfactorial: the problem is in using `CAMLlocal` in [a function that doesn't call `CAMLparam`](https://github.com/fxfactorial/ocaml-linenoise/blob/502250a6001195a07ddc14e42366acb8ebb5970f/src/linenoise_stubs.c#L38).

It's not just a warning; the code doesn't compile with 4.04, which issues the following fatal error:

```
caml/memory.h:224:12: error: ‘caml__frame’ undeclared (first use in this function)
     (void) caml__frame, \
```

Here's the patch in 4.04.0 that changes `CAMLlocal` to enforce the constraint around `CAMLparam`:
 https://github.com/ocaml/ocaml/commit/e61cd5fca2b2b4a4ddb1b28fa50cde29fc81952b

And here's a patch to `linenoise_stubs.c` that fixes the problem:

```diff
diff --git a/src/linenoise_stubs.c b/src/linenoise_stubs.c
index d28de75..a5641b4 100644
--- a/src/linenoise_stubs.c
+++ b/src/linenoise_stubs.c
@@ -35,15 +35,16 @@ static void completion_bridge(const char *buf, linenoiseCompletions *lc)
 
 static char *hints_bridge(const char *buf, int *color, int *bold)
 {
+  CAMLparam0();
   CAMLlocal1(cb_result);
   cb_result = caml_callback(hints_cb, caml_copy_string(buf));
   if (cb_result == Val_none) {
-    return NULL;
+    CAMLreturnT(char *,NULL);
   } else {
     const char *msg = caml_strdup(String_val(Field(Field(cb_result, 0), 0)));
     *color = Int_val(Field(Field(cb_result, 0), 1)) + 31;
     *bold = Bool_val(Field(Field(cb_result, 0), 2));
-    return (char *)msg;
+    CAMLreturnT(char *,msg);
   }
 }
 ```

**Comment by fxfactorial** [comment]
@yallop thank you, but I thought that the CAMLreturn macros were meant for functions that returned to the OCaml side directly whereas this returns to the C library.

**Comment by yallop** [comment]
The `CAMLreturn*` macros are for undoing the effects of `CAMLparam*` and `CAMLlocal*`, not for returning to OCaml.  

[Here](https://github.com/ocaml/ocaml/blob/a3bfa2aaeb049a3f7639a63f2fc2d846a63369b9/byterun/backtrace_prim.c#L127)'s an example in the OCaml runtime of using `CAMLreturnT` in a function that returns to another C function.

**Comment by fxfactorial** [comment]
@yallop Thanks so much! You helped me more deeply understand the OCaml runtime, I am very grateful for that. Build passes now.

**Comment by yallop** [comment]
You're welcome!  And thanks for your patience, and for fixing things up for 4.04.
