### PR TITLE
ubpf.0.1: require dune < 3.0

### PR DESCRIPTION
**Pull request by emillon**
It builds with 2.9.3 but not with dune 3.0.2.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
The error was:
```
#=== ERROR while compiling ubpf.0.1 ===========================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.4.14.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.14/.opam-switch/build/ubpf.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ubpf -j 31
# exit-code            1
# env-file             ~/.opam/log/ubpf-8-c77e48.env
# output-file          ~/.opam/log/ubpf-8-c77e48.out
### output ###
# File "src/dune", line 6, characters 24-27:
# 6 |   (cxx_names ubpf_stubs bpf)
#                             ^^^
# (cd _build/default/src && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -pthread -fPIC -std=c++11 -Iubpf_c/ubpf/vm/inc -g -I /home/opam/.opam/4.14/lib/ocaml -I ubpf_c -o bpf.o -c bpf.cpp)
# bpf.cpp:7:10: fatal error: ubpf.h: No such file or directory
#     7 | #include "ubpf.h"
#       |          ^~~~~~~~
# compilation terminated.
# (cd _build/default/src/ubpf_c/ubpf/vm && /usr/bin/make)
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_vm.o ubpf_vm.c
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_jit_x86_64.o ubpf_jit_x86_64.c
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o ubpf_loader.o ubpf_loader.c
# ar rc libubpf.a ubpf_vm.o ubpf_jit_x86_64.o ubpf_loader.o
# gcc -shared ubpf_vm.o ubpf_jit_x86_64.o ubpf_loader.o -o dllubpf.so
# cc -Wall -Werror -Iinc -O2 -g -fPIC   -c -o test.o test.c
# cc   test.o libubpf.a  -lm -o test
```
Thanks
