### PR TITLE
Package mlgpx.1.0.0

### PR DESCRIPTION
**Pull request by avsm**
### `mlgpx.1.0.0`
Library and CLI for parsing and generating GPS Exchange (GPX) formats
mlgpx is a streaming GPX (GPS Exchange Format) library for OCaml. It provides a portable core library using the xmlm streaming XML parser, with a separate Unix layer for file I/O operations. The library supports the complete GPX 1.1 specification including waypoints, routes, tracks, and metadata with strong type safety and validation.

---
* Homepage: https://tangled.sh/@anil.recoil.org/ocaml-gpx
* Bug tracker: https://tangled.sh/@anil.recoil.org/ocaml-gpx/issues

---
:camel: Pull-request generated by opam-publish v2.5.1

### CODE REVIEW

**Comment by avsm** [comment]
First tangled.sh opam package I think, @mseri! I've filed an issue to allow direct downloads from there in the future; https://tangled.sh/@tangled.sh/core/issues/174

**Comment by dinosaure** [comment]
It seems that the project does not compile on OCaml 5.0 due to `eio.0.12.0`:
```
#=== ERROR while compiling mlgpx.1.0.0 ========================================#
# context              2.3.0 | linux/x86_64 | ocaml-base-compiler.5.0.0 | pinned(https://www.cl.cam.ac.uk/~avsm2/distrib/mlgpx-1.0.0.tbz)
# path                 ~/.opam/5.0/.opam-switch/build/mlgpx.1.0.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p mlgpx -j 255 @install
# exit-code            1
# env-file             ~/.opam/log/mlgpx-7-830d5a.env
# output-file          ~/.opam/log/mlgpx-7-830d5a.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/gpx_eio/.gpx_eio.objs/byte -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/domain-local-await -I /home/opam/.opam/5.0/lib/eio -I /home/opam/.opam/5.0/lib/eio/core -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/lwt-dllist -I /home/opam/.opam/5.0/lib/mtime -I /home/opam/.opam/5.0/lib/optint -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/thread-table -I /home/opam/.opam/5.0/lib/xmlm -I lib/gpx/.gpx.objs/byte -intf-suffix .ml -no-alias-deps -open Gpx_eio__ -o lib/gpx_eio/.gpx_eio.objs/byte/gpx_eio__Gpx_io.cmo -c -impl lib/gpx_eio/gpx_io.ml)
# File "lib/gpx_eio/gpx_io.ml", line 19, characters 16-33:
# 19 |   let content = Eio.Flow.read_all source in
#                      ^^^^^^^^^^^^^^^^^
# Error: Unbound value Eio.Flow.read_all
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I lib/gpx_eio/.gpx_eio.objs/byte -I lib/gpx_eio/.gpx_eio.objs/native -I /home/opam/.opam/5.0/lib/bigstringaf -I /home/opam/.opam/5.0/lib/cstruct -I /home/opam/.opam/5.0/lib/domain-local-await -I /home/opam/.opam/5.0/lib/eio -I /home/opam/.opam/5.0/lib/eio/core -I /home/opam/.opam/5.0/lib/fmt -I /home/opam/.opam/5.0/lib/hmap -I /home/opam/.opam/5.0/lib/lwt-dllist -I /home/opam/.opam/5.0/lib/mtime -I /home/opam/.opam/5.0/lib/optint -I /home/opam/.opam/5.0/lib/ptime -I /home/opam/.opam/5.0/lib/thread-table -I /home/opam/.opam/5.0/lib/xmlm -I lib/gpx/.gpx.objs/byte -I lib/gpx/.gpx.objs/native -intf-suffix .ml -no-alias-deps -open Gpx_eio__ -o lib/gpx_eio/.gpx_eio.objs/native/gpx_eio__Gpx_io.cmx -c -impl lib/gpx_eio/gpx_io.ml)
# File "lib/gpx_eio/gpx_io.ml", line 19, characters 16-33:
# 19 |   let content = Eio.Flow.read_all source in
#                      ^^^^^^^^^^^^^^^^^
# Error: Unbound value Eio.Flow.read_all

```

Also, it seems that the package requires, at least, `eio.1.0.0`.

**Comment by dinosaure** [comment]
Also, the `dev-repo` field is missing on your `opam` file, can you add it?

**Comment by avsm** [comment]
fixes all synced with upstream, thanks @dinosaure!

**Comment by hannesm** [comment]
you're missing the link to the source tarball in the opam file

**Comment by avsm** [comment]
Woops thanks @hannesm, now pushed

**Comment by dinosaure** [comment]
Thanks!
