### PR TITLE
Package spf.2.0.1

### PR DESCRIPTION
**Pull request by andrenth**
### `spf.2.0.1`

OCaml bindings for libspf2

OCaml-SPF provides C bindings for OCaml programs.

---
* Homepage: https://github.com/andrenth/ocaml-spf
* Source repo: https://github.com/andrenth/ocaml-spf.git
* Bug tracker: https://github.com/andrenth/ocaml-spf/issues

---

:camel: Pull-request generated by opam-publish v0.3.5

### CODE REVIEW

**Comment by jpdeplaix** [comment]
On CentOS ```libspf2-devel``` seems to be in the EPEL repository. Could you change the centos line accordingly (something like ```[["centos"] ["epel-release" "libspf2-devel"]]```).
Otherwise everything seems good.
If you don't have time I'll merge it later today and make a PR afterwards.

**Comment by jpdeplaix** [comment]
Mmh, looks like I spoke too soon.
There is an error on Alpine:
```
#=== ERROR while compiling spf.2.0.1 ==========================================#
# context              2.0.0~rc | linux/x86_64 | ocaml-base-compiler.4.05.0 | file:///home/opam/src
# path                 ~/.opam/4.05.0/.opam-switch/build/spf.2.0.1
# command              ~/.opam/4.05.0/bin/jbuilder build -p spf -j 71
# exit-code            1
# env-file             ~/.opam/log/spf-16-899f4c.env
# output-file          ~/.opam/log/spf-16-899f4c.out
### output ###
#       ocamlc src/spf_stubs.o (exit 2)
# (cd _build/default/src && /home/opam/.opam/4.05.0/bin/ocamlc.opt -g -ccopt -Wall -ccopt -Werror -o spf_stubs.o spf_stubs.c)
# In file included from /usr/include/spf2/spf_dns.h:115:0,
#                  from /usr/include/spf2/spf_server.h:22,
#                  from /usr/include/spf2/spf.h:27,
#                  from spf_stubs.c:8:
# /usr/include/spf2/spf_dns_rr.h:64:5: error: unknown type name 'time_t'
#      time_t     ttl;  /**< Raw TTL.   */
#      ^~~~~~
# /usr/include/spf2/spf_dns_rr.h:65:5: error: unknown type name 'time_t'
#      time_t     utc_ttl; /**< TTL adjusted to UTC.  */
#      ^~~~~~
```

**Comment by jpdeplaix** [comment]
mmh ok. Was it a non-compatible version ?

**Comment by andrenth** [comment]
Well the error says "unknown type name 'time_t'", which means it's probably missing an `#include <time.h>`. Not sure if it's due to some local Alpine patch or different versions... I guess I could add the include in ocaml-spf itself, then it should work.

Let me try that.

**Comment by andrenth** [comment]
Yep, adding the include allows it to build on Alpine, so I've released 2.0.2 with that change: #11530

**Comment by jpdeplaix** [comment]
I'm closing this one as #11530 has been merged. Feel free to reopen it if you wanted it to be merged as well.
