### PR TITLE
optal.0.3

### PR DESCRIPTION
**Pull request by zapashcanon**

### CODE REVIEW

**Comment by zapashcanon** [comment]
@kit-ty-kate, thanks for fixing the minimal version, I was about to fix it. I upstreamed the change.

**Comment by kit-ty-kate** [comment]
This package failed to compile with OCaml < 4.07:
```
#=== ERROR while compiling optal.0.3 ==========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/ocamlpro/optal/archive/0.3.tar.gz)
# path                 ~/.opam/4.06/.opam-switch/build/optal.0.3
# command              ~/.opam/4.06/bin/dune build -p optal -j 72 @install
# exit-code            1
# env-file             ~/.opam/log/optal-23-c4933c.env
# output-file          ~/.opam/log/optal-23-c4933c.out
### output ###
#     ocamlopt src/.optal.eobjs/native/dune__exe__Value.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlopt.opt -w -40 -g -I src/.optal.eobjs/byte -I src/.optal.eobjs/native -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/jsonm -I /home/opam/.opam/4.06/lib/uchar -I /home/opam/.opam/4.06/lib/uutf -intf-suffix .ml -no-alias-deps -open Dune__exe -o src/.optal.eobjs/native/dune__exe__Value.cmx -c -impl src/value.ml)
# File "src/value.ml", line 53, characters 26-40:
# Error: Unbound module Stdlib
```
I've fixed it by requiring at least OCaml 4.07, however if you want to stay compatible with 4.05 and 4.06 you can use the `stdlib-shims` package in a later release or something. This requires a change in the source code on your end though.

**Comment by zapashcanon** [comment]
It's OK not to support OCaml < 4.07. Thanks again.

**Comment by kit-ty-kate** [comment]
Thanks!
