### ISSUE TITLE
camlimages fails to build on OS X 10.8.3 w/ MacPorts

### ISSUE THREAD

**Issue by pvernaza** [ocaml/opam-repository#649]
camlimages fails to build on OS X 10.8.3, using MacPorts to install external dependencies.  It seems the problem is due to redefinition of common types in the tiff library.  The problem is likely the same as that reported here: http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/graphics/camlimages/distinfo?rev=1.10;content-type=text/plain
### stderr

...[truncated]
/Users/vernaza/.opam/4.00.1/lib/ocaml/caml/compatibility.h:312:1: warning: this is the location of the previous definition
In file included from /opt/local/include/tiffio.h:33,
                 from tiffwrite.c:29:
/opt/local/include/tiff.h:77: error: redefinition of typedef ‘int64’
/Users/vernaza/.opam/4.00.1/lib/ocaml/caml/config.h:129: error: previous declaration of ‘int64’ was here
/opt/local/include/tiff.h:78: error: redefinition of typedef ‘uint64’
/Users/vernaza/.opam/4.00.1/lib/ocaml/caml/config.h:130: error: previous declaration of ‘uint64’ was here
**\* omake: targets were not rebuilt because of errors:
   src/tiffwrite.o
      depends on: src/tiffwrite.c

'opam install camlimages' failed.
