### PR TITLE
Update lwt.* availability predicates (incompatible with 4.05).

### PR DESCRIPTION
**Pull request by mfp**

### CODE REVIEW

**Comment by mfp** [comment]
This commits merely make the corresponding Lwt versions unavailable on OCaml versions they are known not to work with (mostly 4.05 due to the `O_KEEPEXEC` constructor added to `Unix.open_flag`), so they should not break any other packages.

I've taken a cursory look at some of the reverse dependencies that fail to build/install after these changes, and AFAICS they are failing on their own for reasons unrelated to Lwt.

Some examples:

```
arakoon:
- File "src/tools/arakoon_logger.ml", line 96, characters 10-18:
- Error: Unbound module Sign
- Command exited with code 2. 

brotli:
# gcc: error: unrecognized command line option '-fsanitize-undefined-trap-on-error'
# Command exited with code 2.

multipart-form-data:
# File "lib/multipart.ml", line 128, characters 2-23:
# Error: Unbound value Stringext.chop_prefix
# Command exited with code 2.

rashell:
# ===> manual (install)
# install -d -o opam -g opam /home/opam/.opam/ocaml-base-compiler.4.03.0/share/doc/broken/html
# (cd broken_html && sh -c '(find $1 -depth $3 | cpio -dump $2 >/dev/null 2>&1) && find $1 -depth $3 -type d -exec chmod 755 $2/{} \; && find $1 -depth $3 -type f -exec chmod 440 $2/{} \;' COPYTREE_DOC . /home/opam/.opam/ocaml-base-compiler.4.03.0/share/doc/broken/html)
# *** Error code 127
# 
# Stop.

(IIRC missing cpio)

uwt:
The following command needs to be run through "sudo":
    apt-get install -qq -yy libuv1-dev
E: Unable to locate package libuv1-dev
OS package installation failed
```
