### ISSUE TITLE
Build error for conduit-lwt 2.1.0

### ISSUE THREAD

**Issue by mjambon** [ocaml/opam-repository#16034]
We're getting the following error when trying to install `conduit-lwt.2.1.0`. This was presumably introduced by https://github.com/ocaml/opam-repository/pull/16015. I'm looking into it.
```
[2020-03-17T19:08:59.139Z] #=== ERROR while compiling conduit-lwt-unix.2.1.0 =============================#
[2020-03-17T19:08:59.139Z] # context              2.0.4 | linux/x86_64 | ocaml-base-compiler.4.08.0 | git+https://github.com/ocaml/opam-repository.git
[2020-03-17T19:08:59.139Z] # path                 /opt/forallsecure/mayhem-se/4.08.0/.opam-switch/build/conduit-lwt-unix.2.1.0
[2020-03-17T19:08:59.139Z] # command              /opt/forallsecure/mayhem-se/4.08.0/bin/dune build -p conduit-lwt-unix -j 39
[2020-03-17T19:08:59.139Z] # exit-code            1
[2020-03-17T19:08:59.139Z] # env-file             /opt/forallsecure/mayhem-se/log/conduit-lwt-unix-365-965fed.env
[2020-03-17T19:08:59.139Z] # output-file          /opt/forallsecure/mayhem-se/log/conduit-lwt-unix-365-965fed.out
[2020-03-17T19:08:59.139Z] ### output ###
[2020-03-17T19:08:59.139Z] # [...]
[2020-03-17T19:08:59.139Z] #       ocamlc lwt-unix/.conduit_lwt_unix.objs/byte/conduit_lwt_unix.{cmo,cmt} (exit 2)
[2020-03-17T19:08:59.139Z] # (cd _build/default && /opt/forallsecure/mayhem-se/4.08.0/bin/ocamlc.opt -w -40 -g -bin-annot -I lwt-unix/.conduit_lwt_unix.objs/byte -I /opt/forallsecure/mayhem-se/4.08.0/lib/astring -I /opt/forallsecure/mayhem-se/4.08.0/lib/base/caml -I /opt/forallsecure/mayhem-se/4.08.0/lib/bytes -I /opt/forallsecure/mayhem-se/4.08.0/lib/conduit -I /opt/forallsecure/mayhem-se/4.08.0/lib/conduit-lwt -I /opt/[...]
[2020-03-17T19:08:59.139Z] # File "lwt-unix/conduit_lwt_unix.ml", line 85, characters 16-35:
[2020-03-17T19:08:59.139Z] # 85 |   | `Socket of (Lwt_unix.file_descr [@sexp.opaque])
[2020-03-17T19:08:59.139Z] #                      ^^^^^^^^^^^^^^^^^^^
[2020-03-17T19:08:59.139Z] # Error: Unbound value Lwt_unix.file_descr_of_sexp
[2020-03-17T19:08:59.139Z] #     ocamlopt lwt-unix/.conduit_lwt_unix.objs/native/conduit_lwt_unix.{cmx,o} (exit 2)
[2020-03-17T19:08:59.140Z] # (cd _build/default && /opt/forallsecure/mayhem-se/4.08.0/bin/ocamlopt.opt -w -40 -g -I lwt-unix/.conduit_lwt_unix.objs/byte -I lwt-unix/.conduit_lwt_unix.objs/native -I /opt/forallsecure/mayhem-se/4.08.0/lib/astring -I /opt/forallsecure/mayhem-se/4.08.0/lib/base/caml -I /opt/forallsecure/mayhem-se/4.08.0/lib/bytes -I /opt/forallsecure/mayhem-se/4.08.0/lib/conduit -I /opt/forallsecure/mayhem-s[...]
[2020-03-17T19:08:59.140Z] # File "lwt-unix/conduit_lwt_unix.ml", line 85, characters 16-35:
[2020-03-17T19:08:59.140Z] # 85 |   | `Socket of (Lwt_unix.file_descr [@sexp.opaque])
[2020-03-17T19:08:59.140Z] #                      ^^^^^^^^^^^^^^^^^^^
[2020-03-17T19:08:59.140Z] # Error: Unbound value Lwt_unix.file_descr_of_sexp
```

**Comment by kit-ty-kate** [comment]
cc @hannesm

**Comment by mjambon** [comment]
This is with `ppx_sexp_conv v0.12.0`.

**Comment by hannesm** [comment]
I did not change anything sexp related, maybe @avsm did?

**Comment by mjambon** [comment]
It's this commit by @avsm:
https://github.com/mirage/ocaml-conduit/commit/54af1acb4e74620aafab4d6acc98975535b63e10#diff-7cb62769efef1a71cd4eb0ec32d355feR85

It looks like the `[@sexp.opaque]` isn't working like it's supposed to. I haven't tested with a higher version of the `ppx_sexp_conv` package. Maybe it's fixed in `ppx_sexp_conv v0.13.0` or later.

**Comment by avsm** [comment]
It's definitely working in v0.13.0 -- can you try that and i'll fix the constraints if so?

**Comment by avsm** [comment]
if you're stuck with v0.12 for some reason, can cut a point release of conduit with the old sexp style as well

**Comment by hannesm** [comment]
to me it sounds like raising the lower bounds is a good idea in any case (to avoid others running in this issue)

**Comment by mjambon** [comment]
@avsm We have a dependency that requires v0.12. We can use the previous version of conduit, that's no problem for us. Thank you all @avsm @hannesm @kit-ty-kate !

**Comment by avsm** [comment]
Glad to help!
