### ISSUE TITLE
`metrics.0.1.0` does not compile with OCaml 5.0

### ISSUE THREAD

**Issue by dinosaure** [ocaml/opam-repository#21869]
```
#=== ERROR while compiling metrics.0.1.0 ======================================#
# context              2.1.2 | linux/x86_64 | ocaml-variants.5.0.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/metrics.0.1.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p metrics -j 31
# exit-code            1
# env-file             ~/.opam/log/metrics-23-807ed4.env
# output-file          ~/.opam/log/metrics-23-807ed4.out
### output ###
# File "dune-project", line 3, characters 11-14:
# 3 | (using fmt 1.0)
#                ^^^
# Warning: Version 1.0 of integration with automatic formatters is not
# supported until version 1.4 of the dune language.
# There are no supported versions of this extension in version 1.1 of the dune
# language.
# 
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I src/core/.metrics.objs/byte -I src/core/.metrics.objs/native -I /home/opam/.opam/5.0/lib/fmt -intf-suffix .ml -no-alias-deps -o src/core/.metrics.objs/native/metrics.cmx -c -impl src/core/metrics.ml)
# File "src/core/metrics.ml", line 154, characters 38-56:
# 154 |   let compare (Src src0) (Src src1) = Pervasives.compare src0.uid src1.uid
#                                             ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Pervasives
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/core/.metrics.objs/byte -I /home/opam/.opam/5.0/lib/fmt -intf-suffix .ml -no-alias-deps -o src/core/.metrics.objs/byte/metrics.cmo -c -impl src/core/metrics.ml)
# File "src/core/metrics.ml", line 154, characters 38-56:
# 154 |   let compare (Src src0) (Src src1) = Pervasives.compare src0.uid src1.uid
#                                             ^^^^^^^^^^^^^^^^^^
# Error: Unbound module Pervasives
```
