### ISSUE TITLE
current_docker.0.1 strange failure

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/opam-repository#16216]
A strange failure appeared when building `current_docker.0.1` in https://github.com/ocaml/opam-repository/pull/16214
```
#=== ERROR while compiling current_docker.0.1 =================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.10.0 | file:///home/opam/opam-repository
# path                 ~/.opam/4.10/.opam-switch/build/current_docker.0.1
# command              ~/.opam/4.10/bin/dune build -p current_docker -j 72
# exit-code            1
# env-file             ~/.opam/log/current_docker-25-421a5f.env
# output-file          ~/.opam/log/current_docker-25-421a5f.out
### output ###
#       ocamlc plugins/docker/.current_docker.objs/byte/current_docker__Build.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.10/bin/ocamlc.opt -w -40 -g -bin-annot -I plugins/docker/.current_docker.objs/byte -I /home/opam/.opam/4.10/lib/asetmap -I /home/opam/.opam/4.10/lib/astring -I /home/opam/.opam/4.10/lib/base/caml -I /home/opam/.opam/4.10/lib/biniou -I /home/opam/.opam/4.10/lib/bos -I /home/opam/.opam/4.10/lib/bytes -I /home/opam/.opam/4.10/lib/cmdliner -I /home/opam/.opam/4.10/lib/current -I /home/opam/.opam/4.10/lib/current/cache -I /home/opam/.opam/4.10/lib/current/term -I /home/opam/.opam/4.10/lib/current_git -I /home/opam/.opam/4.10/lib/dockerfile -I /home/opam/.opam/4.10/lib/duration -I /home/opam/.opam/4.10/lib/easy-format -I /home/opam/.opam/4.10/lib/fmt -I /home/opam/.opam/4.10/lib/fpath -I /home/opam/.opam/4.10/lib/irmin-watcher -I /home/opam/.opam/4.10/lib/logs -I /home/opam/.opam/4.10/lib/lwt -I /home/opam/.opam/4.10/lib/lwt-dllist -I /home/opam/.opam/4.10/lib/lwt/unix -I /home/opam/.opam/4.10/lib/mmap -I /home/opam/.opam/4.10/lib/ocaml-migrate-parsetree -I /home/opam/.opam/4.10/lib/ocaml/compiler-libs -I /home/opam/.opam/4.10/lib/ocaml/threads -I /home/opam/.opam/4.10/lib/ocplib-endian -I /home/opam/.opam/4.10/lib/ocplib-endian/bigstring -I /home/opam/.opam/4.10/lib/parsexp -I /home/opam/.opam/4.10/lib/ppx_derivers -I /home/opam/.opam/4.10/lib/ppx_deriving/api -I /home/opam/.opam/4.10/lib/ppx_deriving/runtime -I /home/opam/.opam/4.10/lib/ppx_deriving_yojson -I /home/opam/.opam/4.10/lib/ppx_deriving_yojson/runtime -I /home/opam/.opam/4.10/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/4.10/lib/ppx_tools -I /home/opam/.opam/4.10/lib/prometheus -I /home/opam/.opam/4.10/lib/re -I /home/opam/.opam/4.10/lib/result -I /home/opam/.opam/4.10/lib/rresult -I /home/opam/.opam/4.10/lib/seq -I /home/opam/.opam/4.10/lib/sexplib -I /home/opam/.opam/4.10/lib/sexplib0 -I /home/opam/.opam/4.10/lib/sqlite3 -I /home/opam/.opam/4.10/lib/stdlib-shims -I /home/opam/.opam/4.10/lib/yojson -no-alias-deps -open Current_docker__ -o plugins/docker/.current_docker.objs/byte/current_docker__Build.cmo -c -impl plugins/docker/build.pp.ml)
# File "plugins/docker/build.ml", line 63, characters 16-27:
# 63 |   dockerfile |> Option.iter (fun contents ->
#                      ^^^^^^^^^^^
# Alert deprecated: module Option
# Access modules via the Migrate_parsetree toplevel module. Use Migrate_parsetree.Option instead.
# File "plugins/docker/build.ml", line 63, characters 16-27:
# 63 |   dockerfile |> Option.iter (fun contents ->
#                      ^^^^^^^^^^^
# Error: Unbound value Option.iter
```
cc @talex5 do you know what to constrain? `ocaml-migrate-parsetree` maybe?

**Comment by talex5** [comment]
Wow, yes, looks like `ocaml-migrate-parsetree` just added a new, top-level, `Option` module that conflicts with the stdlib one. Won't this break almost every package using it?

**Comment by avsm** [comment]
That's definitely not intended in ocaml-migrate-parsetree.  Conflicting with omp 1.7.1 should workaround this for now. @diml looks like this was introduced in https://github.com/ocaml-ppx/ocaml-migrate-parsetree/commit/3213780730a7c058199ad75e73ff5b05afa23465

**Comment by avsm** [comment]
Thanks for the quick fix!
