### PR TITLE
make older utop incompatible with ocamlfind 1.5.6

### PR DESCRIPTION
**Pull request by diml**

### CODE REVIEW

**Comment by samoht** [comment]
Old versions of utop doesn't compile on recent versions of OCaml. Maybe add a compiler constraint?

```
#=== ERROR while installing utop.1.12 =========================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -build
# path         /home/travis/.opam/system/build/utop.1.12
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/utop.1.12/utop-8772-e1320e.env
# stdout-file  /home/travis/.opam/system/build/utop.1.12/utop-8772-e1320e.out
# stderr-file  /home/travis/.opam/system/build/utop.1.12/utop-8772-e1320e.err
### stdout ###
# [...]
# File "src/lib/uTop.ml", line 171, characters 23-67:
# Warning 3: deprecated: Format.pp_set_all_formatter_output_functions
# Use Format.pp_set_formatter_out_functions instead.
# File "src/lib/uTop.ml", line 237, characters 6-1108:
# Warning 8: this pattern-matching is not exhaustive.
# Here is an example of a value that is not matched:
# Ill_formed_ast (_, _)
# File "src/lib/uTop.ml", line 346, characters 19-30:
# Error: Unbound module Convenience
# Command exited with code 2.
### stderr ###
# File "setup.ml", line 254, characters 8-26:
# Warning 3: deprecated: String.set
# Use Bytes.set instead.
# File "setup.ml", line 2419, characters 6-24:
# Warning 3: deprecated: Lazy.lazy_from_fun
# Use Lazy.from_fun instead.
# E: Failure("Command ''/usr/bin/ocamlbuild' syntax/optcomp.cma src/lib/utop.cma src/lib/utop.cmxa src/lib/utop.a src/lib/utop.cmxs src/camlp4/utop-camlp4.cma src/camlp4/utop-camlp4.cmxa src/camlp4/utop-camlp4.a src/camlp4/utop-camlp4.cmxs src/top/uTop_top.byte src/top/uTop_top_full.byte -tag debug' terminated with error code 10")
```

**Comment by diml** [comment]
I set the upper bound to 4.01 for all versions < 1.15 as versions >= 1.16 depend on OCaml >= 4.01, but I didn't check it works.

**Comment by avsm** [comment]
Looks like utop 1.10 doesnt want to compile on ocaml 4.01 either...

**Comment by samoht** [comment]
And on 4.00

```
#=== ERROR while installing utop.1.10 =========================================#
# opam-version 1.2.2
# os           linux
# command      make install
# path         /home/travis/.opam/system/build/utop.1.10
# compiler     system (4.00.1)
# exit-code    2
# env-file     /home/travis/.opam/system/build/utop.1.10/utop-7676-8b8e2c.env
# stdout-file  /home/travis/.opam/system/build/utop.1.10/utop-7676-8b8e2c.out
# stderr-file  /home/travis/.opam/system/build/utop.1.10/utop-7676-8b8e2c.err
### stdout ###
# [...]
# pkg_camlp4: .......................................... /usr/lib/ocaml/camlp4
# pkg_camlp4_quotations_o: ............................. /usr/lib/ocaml/camlp4
# pkg_findlib: ......................................... /home/travis/.opam/system/lib/findlib
# pkg_lambda_term: ..................................... /home/travis/.opam/system/lib/lambda-term
# pkg_lwt_syntax: ...................................... /home/travis/.opam/system/lib/lwt
# pkg_threads: ......................................... /usr/lib/ocaml
# ocamldoc: ............................................ /usr/bin/ocamldoc
# gzip: ................................................ /bin/gzip
# 
# ./setup.exe -install 
### stderr ###
# ocamlfind: Package utop is already installed
#  - (file /home/travis/.opam/system/lib/utop/META already exists)
# E: Failure("Command ''/home/travis/.opam/system/bin/ocamlfind' install utop src/lib/META _build/src/camlp4/uTop_camlp4.cmx _build/src/camlp4/uTop_camlp4.cmi _build/src/camlp4/utop-camlp4.cmxs _build/src/camlp4/utop-camlp4.a _build/src/camlp4/utop-camlp4.cmxa _build/src/camlp4/utop-camlp4.cma src/camlp4/uTop_camlp4.mli _build/src/lib/uTop_styles.cmx _build/src/lib/uTop_complete.cmx _build/src/lib/uTop_token.cmx _build/src/lib/uTop_lexer.cmx _build/src/lib/uTop_version.cmx _build/src/lib/uTop_private.cmx _build/src/lib/uTop_main.cmx _build/src/lib/uTop.cmx _build/src/lib/uTop_main.cmi _build/src/lib/uTop.cmi _build/src/lib/utop.cmxs _build/src/lib/utop.a _build/src/lib/utop.cmxa _build/src/lib/utop.cma src/lib/uTop_main.mli src/lib/uTop.mli' terminated with error code 2")
# make: *** [install] Error 1
```

**Comment by lefessan** [comment]
Hi, Any news on this PR ? It is now conflicting with the current `opam` files of `utop`.

Also, beware that the build instructions still contain `[ "ocaml" "setup.ml" "-install"]`, which should be removed now that you have added the `install:` header.

**Comment by diml** [comment]
I rebased the PR

> Also, beware that the build instructions still contain [ "ocaml" "setup.ml" "-install"], which should be removed now that you have added the install: header.

Ah, thanks. I removed these, that should fix the last errors

**Comment by lefessan** [comment]
utop.1.6 cannot compile on ocaml version < 4.01.0, and actually cannot either on ocaml_version > 4.01.0.
Could you update just that `opam` file ?

**Comment by diml** [comment]
done

**Comment by lefessan** [comment]
And another one: utop.1.15 can only compile on ocaml_version >= 4.00.0
