### PR TITLE
easy-format < 1.3.3 is not compatible with OCaml 5

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
The deprecated `Format.pp_get_formatter_tag_functions` was removed. Upstream easy-format is already fixed and has two versions that work on OCaml 5.0 so the migration shouldn't be overly painful.

Found this issue as part of the minimum-version build on #21523 where it picks an older version of easy-format on OCaml 5.0 and thus the build fails.

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
Log for future reference:
```
#=== ERROR while compiling easy-format.1.3.2 ==================================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-variants.5.0.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/easy-format.1.3.2
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p easy-format -j 31
# exit-code            1
# env-file             ~/.opam/log/easy-format-10-07befa.env
# output-file          ~/.opam/log/easy-format-10-07befa.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I src/.easy_format.objs/byte -I src/.easy_format.objs/native -intf-suffix .ml -no-alias-deps -o src/.easy_format.objs/native/easy_format.cmx -c -impl src/easy_format.ml)
# File "src/easy_format.ml", line 203, characters 16-46:
# 203 |     let tagf0 = pp_get_formatter_tag_functions fmt () in
#                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value pp_get_formatter_tag_functions
# Hint: Did you mean pp_get_formatter_stag_functions?
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I src/.easy_format.objs/byte -intf-suffix .ml -no-alias-deps -o src/.easy_format.objs/byte/easy_format.cmo -c -impl src/easy_format.ml)
# File "src/easy_format.ml", line 203, characters 16-46:
# 203 |     let tagf0 = pp_get_formatter_tag_functions fmt () in
#                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value pp_get_formatter_tag_functions
# Hint: Did you mean pp_get_formatter_stag_functions?
```

**Comment by kit-ty-kate** [comment]
Thanks
