### PR TITLE
amqp-client: Fix compilation errors w. 4.0.4+beta

### PR DESCRIPTION
**Pull request by andersfugmann**

### CODE REVIEW

**Comment by yallop** [comment]
The [4.04 build is failing](https://travis-ci.org/ocaml/opam-repository/jobs/156032964):

```
# [...]
# ../clib/clib.a(lm_terminfo.o): In function `caml_tgetstr':
# /home/travis/.opam/4.04.0+beta1/build/omake.0.9.8.6-0.rc1/src/clib/lm_terminfo.c:72: undefined reference to `tigetstr'
# ../clib/clib.a(lm_terminfo.o): In function `load_terminfo':
# /home/travis/.opam/4.04.0+beta1/build/omake.0.9.8.6-0.rc1/src/clib/lm_terminfo.c:35: undefined reference to `setupterm'
# collect2: error: ld returned 1 exit status
# File "caml_startup", line 1:
# Error: Error during linking
# *** omake: targets were not rebuilt because of errors:
#    src/main/omake.opt
# make: *** [all] Error 2
```

**Comment by andersfugmann** [comment]
AFAICS omake fails to build for ocaml 4.04-beta1. Is seems to be compiling (on my machine on 4.04-beta2 though)

**Comment by andersfugmann** [comment]
Apparently omake does not compile w. ocaml 4.04-beta1, but it seems to work with 4.04-beta2. Is there a way to trigger a rebuild against 4.04-beta2?

**Comment by yallop** [comment]
I've restarted the build so that it picks up `4.04.0+beta2`.
