### ISSUE TITLE
Unable to install aez 0.3

### ISSUE THREAD

**Issue by MisterDA** [ocaml/opam-repository#12930]
Hello,
I get a build failure when trying to install [aez](https://opam.ocaml.org/packages/aez/), with ocaml 4.07.0 and opam 2.0.0.

```
# opam config report
# opam-version      2.0.0 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=arch os-version=unknown
# solver            builtin-mccs+glpk
# install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed
# upgrade-criteria  -removed,-count[version-lag,solution],-new
# jobs              7
# repositories      1 (http) (default repo at fe023e42)
# pinned            0
# current-switch    default
```

```
The following actions will be performed:
  ∗ install aez 0.3

<><> Gathering sources <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[aez.0.3] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions ><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of aez failed at
        "~/.opam/opam-init/hooks/sandbox.sh build make".

#=== ERROR while compiling aez.0.3 ===========================================#
# context     2.0.0 | linux/x86_64 | ocaml-system.4.07.0 | https://opam.ocaml.org#fe023e42
# path        ~/.opam/default/.opam-switch/build/aez.0.3
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/aez-16799-a00279.env
# output-file ~/.opam/log/aez-16799-a00279.out
### output ###
# [...]
# Compiling smt/exception.cmi
# Compiling smt/exception.cmo
# Compiling smt/symbols.cmo
# Compiling smt/ty.cmo
# Compiling smt/term.cmo
# Compiling smt/literal.cmo
# Compiling smt/solver_types.cmo
# Compiling smt/explanation.cmo
# Compiling smt/polynome.cmi
# File "smt/polynome.mli", line 15, characters 5-8:
# Error: Unbound module Num
# make: *** [Makefile:100: smt/polynome.cmi] Error 2



<><> Error report ><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build aez 0.3
└─ 
╶─ No changes have been performed
```

The AEZ package uses the venerable combination of configure and make, with a touch of ocamlfind, but apparently misses the Num package.

Thanks for any help.

**Comment by VanessaCristiny** [comment]
I'm having the same issue!! Did you have any progress?

**Comment by mseri** [comment]
It works with ocaml 4.07.1 for me. I have the following library versions installed:

- num.1.1
- ocamlfind.1.8.0

In particular if ocamlfind is too old, it may get confused about num. Try to see if with these it works for you

**Comment by MisterDA** [comment]
Hi !
I think the problem was that the bundled autotools script did not call ocamlfind correctly. I forked aez, patched some stuff, removed autotools and added an ocamlbuild script. You can find my code here : https://github.com/MisterDA/aez.
