### PR TITLE
[new release] dune (15 packages) (3.8.1)

### PR DESCRIPTION
**Pull request by emillon**
Fast, portable, and opinionated build system

- Project page: <a href="https://github.com/ocaml/dune">https://github.com/ocaml/dune</a>
- Documentation: <a href="https://dune.readthedocs.io/">https://dune.readthedocs.io/</a>

##### CHANGES:

- Fix a crash when using a version of Coq < 8.13 due to the native compiler
  config variable being missing. We now explicitly default to `(mode vo)` for
  these older versions of Coq. (ocaml/dune#7847, fixes ocaml/dune#7846, @Alizter)

- Duplicate installed Coq theories are now allowed with the first appearing in
  COQPATH being preferred. This is inline with Coq's loadpath semantics. This
  fixes an issue with install layouts based on COQPATH such as those found in
  nixpkgs. (ocaml/dune#7790, @Alizter)

- Revert ocaml/dune#7415 and ocaml/dune#7450 (Resolve `ppx_runtime_libraries` in the target context when
  cross compiling) (ocaml/dune#7887, fixes ocaml/dune#7875, @emillon)

### CODE REVIEW

**Comment by avsm** [comment]
Is this a regression? 
https://toxis.caelum.ci.dev/github/ocaml/opam-repository/commit/ea834d8184c5eeff1ce601a1ba68cd1556749e97/variant/compilers,5.0,dune.3.8.1,revdeps,toplevel_backend.v0.15.0

```
#=== ERROR while compiling toplevel_backend.v0.15.0 ===========================#
# context              2.2.0~alpha~dev | linux/x86_64 | ocaml-base-compiler.5.0.0 | file:///home/opam/opam-repository
# path                 ~/.opam/5.0/.opam-switch/build/toplevel_backend.v0.15.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p toplevel_backend -j 71
# exit-code            1
# env-file             ~/.opam/log/toplevel_backend-7-00eff0.env
# output-file          ~/.opam/log/toplevel_backend-7-00eff0.out
### output ###
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlopt.opt -w -40 -g -I .toplevel_backend.objs/byte -I .toplevel_backend.objs/native -I /home/opam/.opam/5.0/lib/base -I /home/opam/.opam/5.0/lib/base/base_internalhash_types -I /home/opam/.opam/5.0/lib/base/caml -I /home/opam/.opam/5.0/lib/base/md5 -I /home/opam/.opam/5.0/lib/base/shadow_stdlib -I /home/opam/.opam/5.0/lib/base_bigstring -I /home/opam/.opam/5.0/lib/base_quickcheck -I /home/opam/.opam/5.0/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.0/lib/bin_prot -I /home/opam/.opam/5.0/lib/bin_prot/shape -I /home/opam/.opam/5.0/lib/core -I /home/opam/.opam/5.0/lib/core/base_for_tests -I /home/opam/.opam/5.0/lib/core/validate -I /home/opam/.opam/5.0/lib/fieldslib -I /home/opam/.opam/5.0/lib/findlib -I /home/opam/.opam/5.0/lib/int_repr -I /home/opam/.opam/5.0/lib/jane-street-headers -I /home/opam/.opam/5.0/lib/ocaml-compiler-libs/common -I /home/opam/.opam/5.0/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/5.0/lib/ocaml/compiler-libs -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_derivers -I /home/opam/.opam/5.0/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_expect/collector -I /home/opam/.opam/5.0/lib/ppx_expect/common -I /home/opam/.opam/5.0/lib/ppx_expect/config -I /home/opam/.opam/5.0/lib/ppx_expect/config_types -I /home/opam/.opam/5.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_here/expander -I /home/opam/.opam/5.0/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_inline_test/config -I /home/opam/.opam/5.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_log/types -I /home/opam/.opam/5.0/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.0/lib/ppxlib -I /home/opam/.opam/5.0/lib/ppxlib/ast -I /home/opam/.opam/5.0/lib/ppxlib/astlib -I /home/opam/.opam/5.0/lib/ppxlib/print_diff -I /home/opam/.opam/5.0/lib/ppxlib/stdppx -I /home/opam/.opam/5.0/lib/ppxlib/traverse_builtins -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/splittable_random -I /home/opam/.opam/5.0/lib/stdio -I /home/opam/.opam/5.0/lib/stdlib-shims -I /home/opam/.opam/5.0/lib/time_now -I /home/opam/.opam/5.0/lib/typerep -I /home/opam/.opam/5.0/lib/variantslib -intf-suffix .ml -no-alias-deps -o .toplevel_backend.objs/native/toplevel_backend.cmx -c -impl toplevel_backend.pp.ml)
# File "toplevel_backend.ml", line 8, characters 24-45:
# 8 | let unsafe_string () = !Clflags.unsafe_string
#                             ^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Clflags.unsafe_string
# (cd _build/default && /home/opam/.opam/5.0/bin/ocamlc.opt -w -40 -g -bin-annot -I .toplevel_backend.objs/byte -I /home/opam/.opam/5.0/lib/base -I /home/opam/.opam/5.0/lib/base/base_internalhash_types -I /home/opam/.opam/5.0/lib/base/caml -I /home/opam/.opam/5.0/lib/base/md5 -I /home/opam/.opam/5.0/lib/base/shadow_stdlib -I /home/opam/.opam/5.0/lib/base_bigstring -I /home/opam/.opam/5.0/lib/base_quickcheck -I /home/opam/.opam/5.0/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/opam/.opam/5.0/lib/bin_prot -I /home/opam/.opam/5.0/lib/bin_prot/shape -I /home/opam/.opam/5.0/lib/core -I /home/opam/.opam/5.0/lib/core/base_for_tests -I /home/opam/.opam/5.0/lib/core/validate -I /home/opam/.opam/5.0/lib/fieldslib -I /home/opam/.opam/5.0/lib/findlib -I /home/opam/.opam/5.0/lib/int_repr -I /home/opam/.opam/5.0/lib/jane-street-headers -I /home/opam/.opam/5.0/lib/ocaml-compiler-libs/common -I /home/opam/.opam/5.0/lib/ocaml-compiler-libs/shadow -I /home/opam/.opam/5.0/lib/ocaml/compiler-libs -I /home/opam/.opam/5.0/lib/parsexp -I /home/opam/.opam/5.0/lib/ppx_assert/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_bench/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_derivers -I /home/opam/.opam/5.0/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_expect/collector -I /home/opam/.opam/5.0/lib/ppx_expect/common -I /home/opam/.opam/5.0/lib/ppx_expect/config -I /home/opam/.opam/5.0/lib/ppx_expect/config_types -I /home/opam/.opam/5.0/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_here/expander -I /home/opam/.opam/5.0/lib/ppx_here/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_inline_test/config -I /home/opam/.opam/5.0/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.0/lib/ppx_log/types -I /home/opam/.opam/5.0/lib/ppx_module_timer/runtime -I /home/opam/.opam/5.0/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.0/lib/ppxlib -I /home/opam/.opam/5.0/lib/ppxlib/ast -I /home/opam/.opam/5.0/lib/ppxlib/astlib -I /home/opam/.opam/5.0/lib/ppxlib/print_diff -I /home/opam/.opam/5.0/lib/ppxlib/stdppx -I /home/opam/.opam/5.0/lib/ppxlib/traverse_builtins -I /home/opam/.opam/5.0/lib/sexplib -I /home/opam/.opam/5.0/lib/sexplib0 -I /home/opam/.opam/5.0/lib/splittable_random -I /home/opam/.opam/5.0/lib/stdio -I /home/opam/.opam/5.0/lib/stdlib-shims -I /home/opam/.opam/5.0/lib/time_now -I /home/opam/.opam/5.0/lib/typerep -I /home/opam/.opam/5.0/lib/variantslib -intf-suffix .ml -no-alias-deps -o .toplevel_backend.objs/byte/toplevel_backend.cmo -c -impl toplevel_backend.pp.ml)
# File "toplevel_backend.ml", line 8, characters 24-45:
# 8 | let unsafe_string () = !Clflags.unsafe_string
#                             ^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound value Clflags.unsafe_string


```

**Comment by emillon** [comment]
No, it doesn't build with dune 3.7.0 either. `Clflags.unsafe_string` doesn't exist in 5.0, and v0.15.0 doesn't have [Kate's patch](https://github.com/janestreet/toplevel_backend/commit/109239bf5f16451bffe530f2a68f7f3316b992ea).

**Comment by avsm** [comment]
Thanks; it's helpful to submit constraint fixes for those kinds of things as you spot them if you get a chance, as it makes future CI runs more useful. I've done this one in #23888
