### PR TITLE
Released ocsigen-i18n.1.0.0

### PR DESCRIPTION
**Pull request by sagotch**

### CODE REVIEW

**Comment by avsm** [comment]
```
        /home/opam/.opam/packages.dev/ocsigen-i18n.1.0.0/1.0.0.tar.gz:
          - 68c8d60877c03ed8fe41880626120627 [expected result]
          - 0793372cbeb81dff2cd17cbb89e8c1e8 [actual result]
```

**Comment by sagotch** [comment]
Yep, actual result is the good one... Fixing it...

**Comment by avsm** [comment]
Fails to build on 4.02.3, needs a constraint

```
### stdout ###
# ocamllex i18n_generate.mll
# 31 states, 626 transitions, table size 2690 bytes
# 2185 additional bytes used for bindings
# ocamlfind ocamlc -package str -linkpkg -o ocsigen-i18n-generator i18n_generate.ml
# ocamlfind ocamlc -package str -package compiler-libs.common -linkpkg -o ocsigen-i18n-rewriter i18n_ppx_common.ml i18n_ppx_rewriter.ml
### stderr ###
# findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /home/opam/.opam/4.02.3/lib/ocaml/compiler-libs, /home/opam/.opam/4.02.3/lib/ocaml
# File "i18n_ppx_rewriter.ml", line 36, characters 6-14:
# Error: Unbound constructor Labelled
# make: *** [Makefile:18: ocsigen-i18n-rewriter] Error 2
```
