### PR TITLE
New release of stone 0.5.1, compatible with -safe-string

### PR DESCRIPTION
**Pull request by Armael**
Additionally, add constraints for old versions of stone that do not compile with ocaml 4.06

### CODE REVIEW

**Comment by gasche** [comment]
Stone *0.1* fails to build on OCaml 4.0{0,1}:

```
# File "src/gen.ml", line 56, characters 28-53:
# Error: Unbound module Markdown_github
# make: *** [stone] Error 2
```

For both OCaml versions the versions of the dependencies are exactly the same:

```
∗  installed camlp4.4.01
∗  installed ocamlbuild.0
∗  installed conf-m4.1
∗  installed ocamlfind.1.7.3
∗  installed base-bytes.legacy
∗  installed config-file.1.2
∗  installed ulex.1.1
∗  installed type_conv.111.13.00
∗  installed re.1.7.1
∗  installed ounit.2.0.6
∗  installed dyntype.0.9.0
∗  installed cow.0.4.0
```

Is there a missing bound on the `cow` package there?

**Comment by gasche** [comment]
If it's easy to fix this build issue, I would recommend doing it. Otherwise let me know and I'll merge.

**Comment by Armael** [comment]
I think you are right. I added a lower bound on cow for stone 0.1 and 0.2.
