### ISSUE TITLE
Sqlite3 fails with 4.07.1+musl+static+flambda

### ISSUE THREAD

**Issue by vog** [ocaml/opam-repository#12923]
This is a follow-up on #12769 and #12832.

While static linking against MUSL works for most packages, it fails for `sqlite3`. I hesitate to file this bug against `sqlite3` unless you tell me this is really their fault.

The following error occurs when installing `sqlite3` in the `4.07.1+musl+static+flambda` switch:

```
#=== ERROR while compiling sqlite3.4.4.1 ======================================#
# context     2.0.0 | linux/x86_64 | ocaml-variants.4.07.1+musl+static+flambda | https://opam.ocaml.org#1cacc413
...
# exit-code   1
...
### output ###
#       ocamlc src/sqlite3_stubs.o (exit 2)
# (cd .../src && .../4.07.1+musl+static+flambda/bin/ocamlc.opt -g -ccopt -g -ccopt -O2 -ccopt -fPIC -ccopt -DPIC -o sqlite3_stubs.o sqlite3_stubs.c)
# sqlite3_stubs.c:39:10: fatal error: sqlite3.h: No such file or directory
#  #include <sqlite3.h>
#           ^~~~~~~~~~~
# compilation terminated.
```

Remarks:

* Tested on Debian with installed `libsqlite3-dev`, which contains all headers as well as static libraries.
* Everything works fine with the plain 4.07.1 switch
* With plain 4.07.1 switch, static linking against GLIBC (instead of MUSL) is possible by adding `-static` to the dune files's `(flags ...)` section.
  * (But this has serious downsides which is why I want to use the `4.07.1+musl+static+flambda` switch instead.)
* Since the build fails early on not finding header files, I assume that the  `4.07.1+musl+static+flambda` switch doesn't pass some required compiler options or environment variables along.

**Comment by copy** [comment]
The problem is that the static switch has `musl-gcc` baked in as the C compiler. `musl-gcc` uses a separate search path for libraries, since they need to compiled against `musl` (not glibc, like the files installed by libsqlite3-dev). On Arch Linux, the path is `/usr/lib/musl/{lib,include}`.

You can compile sqlite3 using musl-gcc and install it into `/usr/lib/musl`:

```
  CC=musl-gcc ./configure --prefix=/usr/lib/musl
```

**Comment by vog** [comment]
Thanks for you comment. This is exactly what I tried a few months ago. However, I then ran into another issue which might be opam/sandbox specific: https://github.com/mmottl/sqlite3-ocaml/issues/34
