### PR TITLE
Package herdtools7.7.55

### PR DESCRIPTION
**Pull request by maranget**
### `herdtools7.7.55`
The herdtools suite for simulating and studying weak memory models

---
* Homepage: http://diy.inria.fr/
* Source repo: git+https://github.com/herd/herdtools7.git
* Bug tracker: http://github.com/herd/herdtools7/issues/

---
:camel: Pull-request generated by opam-publish v2.0.2

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package fails to build on OCaml < 4.08:
```
#=== ERROR while compiling herdtools7.7.55 ====================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(https://github.com/herd/herdtools7/archive/7.55.tar.gz)
# path                 ~/.opam/4.07/.opam-switch/build/herdtools7.7.55
# command              /bin/sh ./dune-build.sh /home/opam/.opam/4.07
# exit-code            1
# env-file             ~/.opam/log/herdtools7-23-3e450d.env
# output-file          ~/.opam/log/herdtools7-23-3e450d.out
### output ###
# File "litmus/CArch_litmus.ml", line 21, characters 7-10:
# Error: Multiple definition of the type name reg.
#        Names must be unique in a given structure or signature.
```
```
#=== ERROR while compiling herdtools7.7.55 ====================================#
# context              2.0.6 | linux/x86_64 | ocaml-base-compiler.4.02.3 | pinned(https://github.com/herd/herdtools7/archive/7.55.tar.gz)
# path                 ~/.opam/4.02/.opam-switch/build/herdtools7.7.55
# command              /bin/sh ./dune-build.sh /home/opam/.opam/4.02
# exit-code            1
# env-file             ~/.opam/log/herdtools7-23-12ca7e.env
# output-file          ~/.opam/log/herdtools7-23-12ca7e.out
### output ###
# File "lib/X86_64Base.ml", line 157, characters 2-24:
# Error: Unbound value String.lowercase_ascii
```

File: packages/herdtools7/herdtools7.7.55/opam [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+bug-reports: "http://github.com/herd/herdtools7/issues/"
+doc: "http://diy.inria.fr/doc/index.html"
+dev-repo: "git+https://github.com/herd/herdtools7.git"
+build: ["sh" "./dune-build.sh" "%{prefix}%"]
+install: ["sh" "./dune-install.sh" "%{prefix}%"]
+# @todo Add "build-doc" field
+# @todo Add "build-test" field
+depends: [
+  "ocaml" {>= "4.02.0"}
+  "dune"
```
Comment (kit-ty-kate) [inline packages/herdtools7/herdtools7.7.55/opam]:
```suggestion
  "dune" {>= "1.2"}
  "ocamlfind" {build}
```
According to your `dune-project` file, this package requires at least dune 1.2. Furthermore, since you're using `dune install`, `ocamlfind` should be installed in the current switch to avoid problems (see https://github.com/ocaml/dune/issues/3025)

**Comment by maranget** [comment]
Hi Kate,

sorry for this by far untested release attempt.

I have several changes to commit, to the .opam file and to the sources. What is the most simple way to proceed ?

--Luc

**Comment by kit-ty-kate** [comment]
> What is the most simple way to proceed ?

Depends on your preferences. Calling opam-publish again with the tag re-uploaded beforehand should work for instance (as long as it's the same version and package, opam publish will just updated this PR, no need to create another one)

**Comment by maranget** [comment]
I have proceeded as you suggested. Expecting success...

**Comment by kit-ty-kate** [comment]
Thanks!
