### PR TITLE
Relax lower bound for sexplib

### PR DESCRIPTION
**Pull request by xclerc**

### CODE REVIEW

File: packages/sexplib/sexplib.v0.9.3/opam [hunk 1]
```diff
@@ -13,4 +13,4 @@ depends: [
   "num"
 ]
 
-available: [ ocaml-version >= "4.06.0" ]
```
Comment (avsm) [inline packages/sexplib/sexplib.v0.9.3/opam]: This doesnt compile on 4.04.2:

```
#=== ERROR while installing sexplib.v0.9.3 ====================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p sexplib -j 2
# path                 /home/opam/.opam/4.04.2/build/sexplib.v0.9.3
# compiler             4.04.2
# exit-code            1
# env-file             /home/opam/.opam/4.04.2/build/sexplib.v0.9.3/sexplib-18-326a35.env
# stdout-file          /home/opam/.opam/4.04.2/build/sexplib.v0.9.3/sexplib-18-326a35.out
# stderr-file          /home/opam/.opam/4.04.2/build/sexplib.v0.9.3/sexplib-18-326a35.err
### stderr ###
# [...]
#     ocamlopt src/sexplib.{cmx,o}
#     ocamlopt unix/lib/sexplib_unix.{cmx,o}
#       ocamlc src0/sexplib0__Sexp.{cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04.2/bin/ocamlc.opt -w -40 -g -bin-annot -no-alias-deps -I src0 -open Sexplib0 -o src0/sexplib0__Sexp.cmo -c -impl src0/sexp.ml)
# File "src0/sexp.ml", line 83, characters 4-21:
# Error: Unbound value Bytes.blit_string
#     ocamlopt src0/sexplib0__Sexp.{cmx,o} (exit 2)
# (cd _build/default && /home/opam/.opam/4.04.2/bin/ocamlopt.opt -w -40 -g -no-alias-deps -I src0 -open Sexplib0 -o src0/sexplib0__Sexp.cmx -c -impl src0/sexp.ml)
# File "src0/sexp.ml", line 83, characters 4-21:
# Error: Unbound value Bytes.blit_string
```

**Comment by xclerc** [comment]
Indeed, I tested on the wrong branch (how embarrassing).
The correct lower bound is 4.05.0.
