### PR TITLE
[new release] pratter (1.0)

### PR DESCRIPTION
**Pull request by gabrielhdt**
An implementation of the Pratt parsing algorithm for first order terms

- Project page: <a href="https://github.com/gabrielhdt/pratter">https://github.com/gabrielhdt/pratter</a>

##### CHANGES:

This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

### Changed
- API: parser uses a data structure passed as argument
- renamed CHANGELOG to CHANGELOG.md

### Added
- Initial version

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
I'm not sure if I inferred your intent correctly but `ocaml 4.0.5` does not exist, I'm guessing you meant `ocaml 4.05` instead so I fixed that. If I'm not correct please say so.

Other than that your tests do not compile on OCaml < 4.07:
```
#=== ERROR while compiling pratter.1.0 ========================================#
# context              2.0.7 | linux/x86_64 | ocaml-base-compiler.4.06.1 | pinned(https://github.com/gabrielhdt/pratter/releases/download/1.0/pratter-1.0.tbz)
# path                 ~/.opam/4.06/.opam-switch/build/pratter.1.0
# command              ~/.opam/4.06/bin/dune build -p pratter -j 31 @install @runtest
# exit-code            1
# env-file             ~/.opam/log/pratter-19-cddc6e.env
# output-file          ~/.opam/log/pratter-19-cddc6e.out
### output ###
#       ocamlc t/.main.eobjs/byte/dune__exe__Main.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -g -bin-annot -I t/.main.eobjs/byte -I /home/opam/.opam/4.06/lib/alcotest -I /home/opam/.opam/4.06/lib/alcotest/engine -I /home/opam/.opam/4.06/lib/astring -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/cmdliner -I /home/opam/.opam/4.06/lib/fmt -I /home/opam/.opam/4.06/lib/re -I /home/opam/.opam/4.06/lib/seq -I /home/opam/.opam/4.06/lib/stdlib-shims -I /home/opam/.opam/4.06/lib/uchar -I /home/opam/.opam/4.06/lib/uuidm -I /home/opam/.opam/4.06/lib/uutf -I .pratter.objs/byte -I .pratter.objs/native -no-alias-deps -o t/.main.eobjs/byte/dune__exe__Main.cmo -c -impl t/main.ml)
# File "t/main.ml", line 73, characters 7-18:
# Error: Unbound value List.to_seq

-       ocamlc t/.main.eobjs/byte/dune__exe__Main.{cmi,cmo,cmt} (exit 2)
- (cd _build/default && /home/opam/.opam/4.06/bin/ocamlc.opt -w -40 -g -bin-annot -I t/.main.eobjs/byte -I /home/opam/.opam/4.06/lib/alcotest -I /home/opam/.opam/4.06/lib/alcotest/engine -I /home/opam/.opam/4.06/lib/astring -I /home/opam/.opam/4.06/lib/bytes -I /home/opam/.opam/4.06/lib/cmdliner -I /home/opam/.opam/4.06/lib/fmt -I /home/opam/.opam/4.06/lib/re -I /home/opam/.opam/4.06/lib/seq -I /home/opam/.opam/4.06/lib/stdlib-shims -I /home/opam/.opam/4.06/lib/uchar -I /home/opam/.opam/4.06/lib/uuidm -I /home/opam/.opam/4.06/lib/uutf -I .pratter.objs/byte -I .pratter.objs/native -no-alias-deps -o t/.main.eobjs/byte/dune__exe__Main.cmo -c -impl t/main.ml)
- File "t/main.ml", line 73, characters 7-18:
- Error: Unbound value List.to_seq
```
I fixed that here by requiring at least OCaml 4.07 during the tests.

Could you return the fixes in your opam file upstream so that they are updated for next release?

**Comment by gabrielhdt** [comment]
Ah sorry I missed this again! I'll do this, thanks a lot.

**Comment by kit-ty-kate** [comment]
Thanks!
