### PR TITLE
Coq 8.8.1 doesn't compile with OCaml 4.08.0

### PR DESCRIPTION
**Pull request by catalin-hritcu**
Here's the error message when trying to compile Coq 8.8.1 with OCaml 4.08.0:
```
#=== ERROR while compiling coq.8.8.1 ==========================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.0 | pinned(https://github.com/coq/coq/archive/V8.8.1.tar.gz)
# path        ~/.opam/4.08.0/.opam-switch/build/coq.8.8.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j7
# exit-code   2
# env-file    ~/.opam/log/coq-13555-af57d6.env
# output-file ~/.opam/log/coq-13555-af57d6.out
### output ###
# 59 |     open Hashset.Combine
# [...]
# Error: Unbound module Hashset
# Hint: Did you mean Hashtbl?
# make[1]: *** [Makefile.build:668: clib/cSet.cmx] Error 2
# File "clib/hashset.ml", line 1:
# Error: Could not find the .cmi file for interface clib/hashset.mli.
# File "clib/cObj.ml", line 1:
# Error: Could not find the .cmi file for interface clib/cObj.mli.
# make[1]: *** [Makefile.build:668: clib/hashset.cmx] Error 2
# make[1]: *** [Makefile.build:668: clib/cObj.cmx] Error 2
# make[1]: Leaving directory '/home/hritcu/.opam/4.08.0/.opam-switch/build/coq.8.8.1'
# make: *** [Makefile:191: submake] Error 2
```

This error doesn't occur with OCaml 4.07.1, so I propose setting an upper bound.

### CODE REVIEW

**Comment by ejgallego** [comment]
This could be due to problems with `camlp5` (cc: #14645 ) , but without seeing the log is hard to know.

We didn't investigate the problem very thoroughly as Coq doesn't use camlp5 anymore, but it could be the case that what is broken is `camlp5` thus the constraint should be added there.

**Comment by catalin-hritcu** [comment]
@ejgallego This should be easy to reproduce, so just give it a try via opam :)

Also, just realized that this problem also affects Coq 8.9.1
```
#=== ERROR while compiling coq.8.9.1 ==========================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.08.0 | pinned(https://github.com/coq/coq/archive/V8.9.1.tar.gz)
# path        ~/.opam/4.08.0/.opam-switch/build/coq.8.9.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j7
# exit-code   2
# env-file    ~/.opam/log/coq-20452-6d07ae.env
# output-file ~/.opam/log/coq-20452-6d07ae.out
### output ###
# [...]
# Error: Could not find the .cmi file for interface clib/cEphemeron.mli.
# make[1]: *** [Makefile.build:753: clib/cMap.cmx] Error 2
# make[1]: *** [Makefile.build:753: clib/cSet.cmx] Error 2
# make[1]: *** [Makefile.build:753: clib/cEphemeron.cmx] Error 2
# File "clib/cObj.ml", line 1:
# Error: Could not find the .cmi file for interface clib/cObj.mli.
# make[1]: *** [Makefile.build:753: clib/cObj.cmx] Error 2
# File "clib/hashset.ml", line 1:
# Error: Could not find the .cmi file for interface clib/hashset.mli.
# make[1]: *** [Makefile.build:753: clib/hashset.cmx] Error 2
# make[1]: Leaving directory '/home/hritcu/.opam/4.08.0/.opam-switch/build/coq.8.9.1'
# make: *** [Makefile:166: submake] Error 2
```

**Comment by catalin-hritcu** [comment]
I've anyway uploaded the log files now, in case it speeds things up:
[coq-21111-6d07ae.info.txt](https://github.com/ocaml/opam-repository/files/3489267/coq-21111-6d07ae.info.txt)
[coq-21111-6d07ae.out.txt](https://github.com/ocaml/opam-repository/files/3489268/coq-21111-6d07ae.out.txt)

**Comment by ejgallego** [comment]
Thanks @catalin-hitcru , it will affect all coq versions < 8.9 as what is broken is camlp5.

**Comment by catalin-hritcu** [comment]
@ejgallego So what can we do?

1. Should we file this against camlp5? What are the chances it will get fixed promptly?

2. And in the meantime should we set on OCaml bound of < 4.08.0 for all Coq versions < 8.9.0?

**Comment by garrigue** [comment]
The same fix as in #14668 should work.

**Comment by catalin-hritcu** [comment]
Cool, so I'll close this PR and wait instead for #14668 to be applied to older Coq versions too.

**Comment by garrigue** [comment]
At least I could compile 8.9.1 and 8.8.1 using https://github.com/camlp5/camlp5/pull/46 (now merged), but I didn't test extensively after compilation (just compiled coq-mathcomp-algebra on 8.9.1).
I don't know if this is sufficient for older versions of coq.

**Comment by catalin-hritcu** [comment]
@garrigue: I could compile Coq 8.9.1 now using opam and OCaml 4.8.0, but the same is not true for Coq 8.8.1, for which I still get the same error as before: [coq-27563-6d07ae.out.txt](https://github.com/ocaml/opam-repository/files/3503232/coq-27563-6d07ae.out.txt)  Is this supposed to work via opam already?

**Comment by garrigue** [comment]
The fix in opam now is for coq 8.9.1 only, but there is another fix already merged in camlp5, that just awaits a new release of camlp5 (needed for 4.08.1 anyway)
