### PR TITLE
Removing denpendency to Javalib 3.0

### PR DESCRIPTION
**Pull request by anscoil**

### CODE REVIEW

**Comment by anscoil** [comment]
All the 2.0 tests fail but I can't correct it in these packages versions.

**Comment by kit-ty-kate** [comment]
Following the logs, only `sawja.1.5` is failing. It probably needs a tighter constraint:
```
# /home/opam/.opam/4.07/bin/ocamlfind ocamlc -g -w Aer -annot -package javalib -I dataflow_analyses/ -I heap_parser/ -c jCodePP.mli
# File "jCodePP.mli", line 23, characters 0-17:
# Warning 33: unused open JControlFlow.
# /home/opam/.opam/4.07/bin/ocamlfind ocamlc -g -w Aer -annot -package javalib -I dataflow_analyses/ -I heap_parser/ -c jBir.mli
# File "jBir.mli", line 64, characters 16-50:
# Error: Unbound module type Javalib_pack.JBasics.GenericSetSig
# Makefile:135: recipe for target 'jBir.cmi' failed
# make[1]: *** [jBir.cmi] Error 2
# make[1]: Leaving directory '/home/opam/.opam/4.07/.opam-switch/build/sawja.1.5/src'
# Makefile:25: recipe for target 'sawja' failed
# make: *** [sawja] Error 2
```

**Comment by kit-ty-kate** [comment]
I just went through your commit history and that might do it.

Side note: having undocumentated (I didn't see anything in the Changelog file) API change in minor versions is bad practice. That said, everybody make that kind of mistakes (I do and did too) and it's not a serious issue ^^'

**Comment by kit-ty-kate** [comment]
yep, all good. Thanks!

**Comment by anscoil** [comment]
Thank you !
