### PR TITLE
[new release] colibri2 (4 packages) (0.5)

### PR DESCRIPTION
**Pull request by bobot**
A CP solver for smtlib

- Project page: <a href="https://colibri.frama-c.com">https://colibri.frama-c.com</a>

##### CHANGES:

  - Add propagators for FP and BV theory
  - Add theory of arrays, sequence, and n-sequence (Hichem Rami Ait-El-Hara)
  - Use linear boolean ring for bv
  - Use labelled union-find for LRA
  - Fix multiplication domain
  - Many simplifications and improvements
  - propagators for abs, power, modulo (euclidean, floor, truncate)

### CODE REVIEW

File: packages/colibrics/colibrics.0.5/opam [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+description: "The core of Colibrics is formally proved using Why3."
+maintainer: ["François Bobot"]
+authors: ["François Bobot"]
+license: "LGPL-2.1-only"
+homepage: "https://colibri.frama-c.com"
+bug-reports: "https://git.frama-c.com/pub/colibrics/issues"
+depends: [
+  "ocaml" {>= "4.12"}
+  "cmdliner" {>= "2.0.0"}
+  "dolmen" {= "0.10"}
```
Comment (mseri) [inline packages/colibrics/colibrics.0.5/opam:13]:
```suggestion
  "colibri2" {= version}
  "dolmen" {= "0.10"}
```

Comment (mseri) [reply packages/colibrics/colibrics.0.5/opam:13]: Due to
```
#=== ERROR while compiling colibrics.0.5 ======================================#
# context              2.5.0 | linux/x86_64 | ocaml-base-compiler.4.12.1 | pinned(https://git.frama-c.com/api/v4/projects/879/packages/generic/colibri2/0.5/colibri2-0.5.tbz)
# path                 ~/.opam/4.12/.opam-switch/build/colibrics.0.5
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p colibrics -j 71 --promote-install-files=false @install @runtest
# exit-code            1
# env-file             ~/.opam/log/colibrics-7-137eb1.env
# output-file          ~/.opam/log/colibrics-7-137eb1.out
### output ###
# File "colibri2/tests/cram/dune", line 2, characters 16-24:
# 2 |  (deps (package colibri2)))
#                     ^^^^^^^^
# Error: Package colibri2 does not exist
# File "colibri2/tests/dune", line 25, characters 21-29:
# 25 | (cram (deps (package colibri2)))
#                           ^^^^^^^^
# Error: Package colibri2 does not exist
```

Comment (bobot) [reply packages/colibrics/colibrics.0.5/opam:13]: Sorry I will go back to this MR, but this fix is wrong. It is just a missing `(package colibri2)` in those cram rule so that they are removed when not compiling colibri2. The fix is simple but I need to add a patch in the  `opam-archive` repository for adding the missing lines.

**Comment by mseri** [comment]
Any update on this?

File: packages/colibri2/colibri2.0.5/opam [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+    "-j"
+    jobs
+    "--promote-install-files=false"
+    "@install"
+    "@runtest" {with-test}
+    "@doc" {with-doc}
+  ]
+  ["dune" "install" "-p" name "--create-install-files" name]
+]
+dev-repo: "git+https://git.frama-c.com/pub/colibrics.git"
```
Comment (mseri) [inline packages/colibri2/colibri2.0.5/opam:61]:
```suggestion
dev-repo: "git+https://git.frama-c.com/pub/colibrics.git"
patches: [ "attach-cram-test-to-package.patch" ]
extra-source "attach-cram-test-to-package.patch" {
  src:
    "https://github.com/ocaml/opam-source-archives/raw/f12d787d1054b279dffcb39383c2bca2bee645cd/patches/colibri2/attach-cram-test-to-package.patch"
  checksum: [
    "sha256=09ab6ba3e81d3a189d9d222cbf59f9123163b1f8d175defb2d53a59a1ec93e5c"
  ]
}
```

Comment (mseri) [reply packages/colibri2/colibri2.0.5/opam:61]: Needs to be merged at github.com/ocaml/opam-source-archives/pull/60 before merging this

File: packages/colibri2/colibri2.0.5/opam [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+  "colibrilib" {= version}
+  "containers" {>= "3.6.1"}
+  "dolmen" {= "0.10"}
+  "dolmen_loop" {= "0.10"}
+  "dolmen_type" {= "0.10"}
+  "dune" {>= "3.7" & >= "3.7"}
+  "dune-build-info" {>= "3.7"}
+  "farith"
+  "gen" {>= "1.0"}
+  "ocaml" {>= "4.12"}
```
Comment (mseri) [inline packages/colibri2/colibri2.0.5/opam]:
```suggestion
  "ocaml" {>= "5.5"}
```
Due to
```
#=== ERROR while compiling colibri2.0.5 =======================================#
# context              2.5.1 | linux/x86_64 | ocaml-base-compiler.5.3.0 | pinned(https://git.frama-c.com/api/v4/projects/879/packages/generic/colibri2/0.5/colibri2-0.5.tbz)
# path                 ~/.opam/5.3/.opam-switch/build/colibri2.0.5
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p colibri2 -j 71 --promote-install-files=false @install
# exit-code            1
# env-file             ~/.opam/log/colibri2-7-0beb4e.env
# output-file          ~/.opam/log/colibri2-7-0beb4e.out
### output ###
# (cd _build/default && /home/opam/.opam/5.3/bin/ocamlc.opt -w -40 -open Containers -g -bin-annot -I colibri2/stdlib/.colibri2_stdlib.objs/byte -I /home/opam/.opam/5.3/lib/base -I /home/opam/.opam/5.3/lib/base/base_internalhash_types -I /home/opam/.opam/5.3/lib/base/caml -I /home/opam/.opam/5.3/lib/base/shadow_stdlib -I /home/opam/.opam/5.3/lib/bigarray-compat -I /home/opam/.opam/5.3/lib/containers -I /home/opam/.opam/5.3/lib/containers/monomorphic -I /home/opam/.opam/5.3/lib/ctypes -I /home/opam/.opam/5.3/lib/ctypes/stubs -I /home/opam/.opam/5.3/lib/either -I /home/opam/.opam/5.3/lib/flint -I /home/opam/.opam/5.3/lib/fmt -I /home/opam/.opam/5.3/lib/integers -I /home/opam/.opam/5.3/lib/jane-street-headers -I /home/opam/.opam/5.3/lib/mtime -I /home/opam/.opam/5.3/lib/mtime/clock -I /home/opam/.opam/5.3/lib/ocaml/str -I /home/opam/.opam/5.3/lib/ocaml/threads -I /home/opam/.opam/5.3/lib/ocaml/unix -I /home/opam/.opam/5.3/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_deriving/runtime -I /home/opam/.opam/5.3/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_inline_test/config -I /home/opam/.opam/5.3/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.3/lib/qcheck-core -I /home/opam/.opam/5.3/lib/re -I /home/opam/.opam/5.3/lib/seq -I /home/opam/.opam/5.3/lib/sexplib0 -I /home/opam/.opam/5.3/lib/stdlib-shims -I /home/opam/.opam/5.3/lib/time_now -I /home/opam/.opam/5.3/lib/trace-tef -I /home/opam/.opam/5.3/lib/trace/core -I /home/opam/.opam/5.3/lib/trace/debug -I /home/opam/.opam/5.3/lib/trace/util -I /home/opam/.opam/5.3/lib/zarith -I colibri2/popop_lib/.colibri2_popop_lib.objs/byte -intf-suffix .ml -no-alias-deps -open Colibri2_stdlib -o colibri2/stdlib/.colibri2_stdlib.objs/byte/colibri2_stdlib__Bitv.cmo -c -impl colibri2/stdlib/bitv.pp.ml)
# File "colibri2/stdlib/bitv.ml", line 248, characters 15-29:
# 248 |     r := !r + (Int64.popcount @@ Bytes.get_int64_ne b i)
#                      ^^^^^^^^^^^^^^
# Error: Unbound value "Int64.popcount"
# (cd _build/default && /home/opam/.opam/5.3/bin/ocamlopt.opt -w -40 -open Containers -g -O3 -bin-annot -unbox-closures -unbox-closures-factor 20 -I colibri2/stdlib/.colibri2_stdlib.objs/byte -I colibri2/stdlib/.colibri2_stdlib.objs/native -I /home/opam/.opam/5.3/lib/base -I /home/opam/.opam/5.3/lib/base/base_internalhash_types -I /home/opam/.opam/5.3/lib/base/caml -I /home/opam/.opam/5.3/lib/base/shadow_stdlib -I /home/opam/.opam/5.3/lib/bigarray-compat -I /home/opam/.opam/5.3/lib/containers -I /home/opam/.opam/5.3/lib/containers/monomorphic -I /home/opam/.opam/5.3/lib/ctypes -I /home/opam/.opam/5.3/lib/ctypes/stubs -I /home/opam/.opam/5.3/lib/either -I /home/opam/.opam/5.3/lib/flint -I /home/opam/.opam/5.3/lib/fmt -I /home/opam/.opam/5.3/lib/integers -I /home/opam/.opam/5.3/lib/jane-street-headers -I /home/opam/.opam/5.3/lib/mtime -I /home/opam/.opam/5.3/lib/mtime/clock -I /home/opam/.opam/5.3/lib/ocaml/str -I /home/opam/.opam/5.3/lib/ocaml/threads -I /home/opam/.opam/5.3/lib/ocaml/unix -I /home/opam/.opam/5.3/lib/ppx_compare/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_deriving/runtime -I /home/opam/.opam/5.3/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_hash/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_inline_test/config -I /home/opam/.opam/5.3/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/5.3/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/5.3/lib/qcheck-core -I /home/opam/.opam/5.3/lib/re -I /home/opam/.opam/5.3/lib/seq -I /home/opam/.opam/5.3/lib/sexplib0 -I /home/opam/.opam/5.3/lib/stdlib-shims -I /home/opam/.opam/5.3/lib/time_now -I /home/opam/.opam/5.3/lib/trace-tef -I /home/opam/.opam/5.3/lib/trace/core -I /home/opam/.opam/5.3/lib/trace/debug -I /home/opam/.opam/5.3/lib/trace/util -I /home/opam/.opam/5.3/lib/zarith -I colibri2/popop_lib/.colibri2_popop_lib.objs/byte -I colibri2/popop_lib/.colibri2_popop_lib.objs/native -intf-suffix .ml -no-alias-deps -open Colibri2_stdlib -o colibri2/stdlib/.colibri2_stdlib.objs/native/colibri2_stdlib__Bitv.cmx -c -impl colibri2/stdlib/bitv.pp.ml)
# File "colibri2/stdlib/bitv.ml", line 248, characters 15-29:
# 248 |     r := !r + (Int64.popcount @@ Bytes.get_int64_ne b i)
#                      ^^^^^^^^^^^^^^
# Error: Unbound value "Int64.popcount"
```


Unfortunately the cram fix did not work. I need to have another look

Comment (bobot) [reply packages/colibri2/colibri2.0.5/opam]: I will go back with a new version, where I will check all of that. Thank you a lot. (Still if you find why there is this problem here because it is working with older version of 5.5, I will be deeply grateful).

Comment (bobot) [reply packages/colibri2/colibri2.0.5/opam]: I need to bump the version of containers to 3.9
