### PR TITLE
[new release] iomux (0.1)

### PR DESCRIPTION
**Pull request by haesbaert**
IO Multiplexer bindings

- Project page: <a href="https://github.com/haesbaert/ocaml-iomux">https://github.com/haesbaert/ocaml-iomux</a>
- Documentation: <a href="https://haesbaert.github.io/ocaml-iomux">https://haesbaert.github.io/ocaml-iomux</a>

##### CHANGES:

* Initial release

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There are a number of warnings and errors triggered by the default C compiler on macOS:
```
#=== ERROR while compiling iomux.0.1 ==========================================#
# context              2.1.4 | macos/x86_64 | ocaml-base-compiler.4.14.1 | pinned(https://github.com/haesbaert/ocaml-iomux/releases/download/v0.1/iomux-0.1.tbz)
# path                 ~/.opam/4.14.1/.opam-switch/build/iomux.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p iomux -j 5 @install
# exit-code            1
# env-file             ~/.opam/log/iomux-12056-04c165.env
# output-file          ~/.opam/log/iomux-12056-04c165.out
### output ###
# File "lib/dune", line 12, characters 9-20:
# 12 |   (names iomux_stubs)))
#               ^^^^^^^^^^^
# (cd _build/default/lib && /usr/bin/cc -O2 -fno-strict-aliasing -fwrapv -pthread -D_FILE_OFFSET_BITS=64 -g -I /Users/mac1000/.opam/4.14.1/lib/ocaml -o iomux_stubs.o -c iomux_stubs.c)
# iomux_stubs.c:88:16: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
#         if (v_sigmask = Val_emptylist)
#             ~~~~~~~~~~^~~~~~~~~~~~~~~
# iomux_stubs.c:88:16: note: place parentheses around the assignment to silence this warning
#         if (v_sigmask = Val_emptylist)
#                       ^
#             (                        )
# iomux_stubs.c:88:16: note: use '==' to turn this assignment into an equality comparison
#         if (v_sigmask = Val_emptylist)
#                       ^
#                       ==
# iomux_stubs.c:101:6: error: implicit declaration of function 'ppoll' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
#         r = ppoll(fds, nfds, timo, psigmask);
#             ^
# iomux_stubs.c:101:6: note: did you mean 'poll'?
# /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/poll.h:113:12: note: 'poll' declared here
# extern int poll(struct pollfd *, nfds_t, int) __DARWIN_ALIAS_C(poll);
#            ^
# 1 warning and 1 error generated.
```

**Comment by haesbaert** [comment]
not really, I'd rather have this out now cause we have a branch in eio that has a use for it and will be unaffected by the bug, next week I can work on version 0.2 and fix both.

**Comment by kit-ty-kate** [comment]
Ok fair enough. Will merge as soon as CI finishes.

**Comment by kit-ty-kate** [comment]
Thanks
