### PR TITLE
[new release] inquire (0.1.0)

### PR DESCRIPTION
**Pull request by tmattio**
An OCaml library to create beautiful interactive CLIs

- Project page: <a href="https://github.com/tmattio/inquire">https://github.com/tmattio/inquire</a>
- Documentation: <a href="https://tmattio.github.io/inquire">https://tmattio.github.io/inquire</a>

##### CHANGES:

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

### Added

- Add `confirm` prompt.
- Add `input` prompt.
- Add `password` prompt.
- Add `raw_list` prompt.

[Unreleased]: https://github.com/tmattio/spin/compare/v0.1.0...HEAD
[0.1.0]: https://github.com/tmattio/spin/releases/tag/v0.1.0

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
This package fails to build with OCaml 4.04 and 4.05 with the following error:
```
# (cd _build/default && /home/opam/.opam/4.04/bin/ocamlc.opt -open Base -g -bin-annot -I lib/.Inquire.objs/byte -I /home/opam/.opam/4.04/lib/base -I /home/opam/.opam/4.04/lib/base/base_internalhash_types -I /home/opam/.opam/4.04/lib/base/caml -I /home/opam/.opam/4.04/lib/base/shadow_stdlib -I /home/opam/.opam/4.04/lib/bytes -I /home/opam/.opam/4.04/lib/camomile -I /home/opam/.opam/4.04/lib/camomile/default_config -I /home/opam/.opam/4.04/lib/camomile/dyn -I /home/opam/.opam/4.04/lib/camomile/lib_default -I /home/opam/.opam/4.04/lib/camomile/library -I /home/opam/.opam/4.04/lib/charInfo_width -I /home/opam/.opam/4.04/lib/lambda-term -I /home/opam/.opam/4.04/lib/lwt -I /home/opam/.opam/4.04/lib/lwt/unix -I /home/opam/.opam/4.04/lib/lwt_log -I /home/opam/.opam/4.04/lib/lwt_log/core -I /home/opam/.opam/4.04/lib/lwt_react -I /home/opam/.opam/4.04/lib/mmap -I /home/opam/.opam/4.04/lib/ocaml/threads -I /home/opam/.opam/4.04/lib/ocplib-endian -I /home/opam/.opam/4.04/lib/react -I /home/opam/.opam/4.04/lib/result -I /home/opam/.opam/4.04/lib/seq -I /home/opam/.opam/4.04/lib/sexplib0 -I /home/opam/.opam/4.04/lib/zed -no-alias-deps -open Inquire__ -o lib/.Inquire.objs/byte/inquire__Raw_list.cmo -c -impl lib/prompts/raw_list.ml)
# File "lib/prompts/raw_list.ml", line 8, characters 6-28:
# Error: Unbound value Caml.int_of_string_opt
#       ocamlc lib/.Inquire.objs/byte/inquire__Input.{cmi,cmo,cmt}
```
An constraint on OCaml might be required

**Comment by kit-ty-kate** [comment]
The archive changed again:
```
[ERROR] The sources of the following couldn't be obtained, aborting:
          - inquire.0.1.0:
            https://github.com/tmattio/inquire/releases/download/v0.1.0/inquire-v0.1.0.tbz (Bad checksum, expected sha256=aa5cf3b1a372a89019ffe52245000f6f80596d4cc81dc5d081397c5dff6b45e3)
```

**Comment by tmattio** [comment]
Hi @kit-ty-kate, thanks for putting the error here!

The checksum in the generated Opam file is wrong, which is strange because I've simply used `dune-release` and it took care of uploading the `tbz` on Github and openning a PR here. Do you have any idea what could have gone wrong?

Worst case I'll just put the checksum manually but I'd like to keep the release automatated.

**Comment by kit-ty-kate** [comment]
Dune should not be tagged as a build dependency (see #14266). Could you return the fixes upstream?

Otherwise this PR is good to go. Thanks!

**Comment by tmattio** [comment]
@kit-ty-kate Will do, thanks! Any reason for increaing the lower bound to `2.0`?

**Comment by kit-ty-kate** [comment]
> @kit-ty-kate Will do, thanks! Any reason for increaing the lower bound to `2.0`?

Because otherwise the compilation will fail with lower versions. You changed the lower-bound in this commit: https://github.com/tmattio/inquire/commit/11e1c4c6121fa1c479a39630695783a3a8af1dcb
