### PR TITLE
Package p4spectec.0.1.0

### PR DESCRIPTION
**Pull request by pacokwon**
### `p4spectec.0.1.0`
P4-SpecTec: A mechanization toolchain for the P4 Programming Language
A mechanization toolchain for the P4 programming language

---
* Homepage: https://github.com/kaist-plrg/p4-spectec
* Source repo: git+https://github.com/kaist-plrg/p4-spectec.git
* Bug tracker: https://github.com/kaist-plrg/p4-spectec/issues

---
:camel: Pull-request generated by opam-publish v3.0.0

### CODE REVIEW

**Comment by jmid** [comment]
There are several CI test failures to look into if you click `opam-ci` pointing here: https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0ded330ca2bcf156ee9cdd6548cdadd458e3cad3

4.14
  - [p4spectec.0.1.0 (failed: Unbound value List.is_empty)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0ded330ca2bcf156ee9cdd6548cdadd458e3cad3/variant/compilers,4.14,p4spectec.0.1.0)
    (failing to build on 4.14 and earlier)

5.5
- p4spectec.0.1.0
  - [lower-bounds (failed: Unbound module El)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0ded330ca2bcf156ee9cdd6548cdadd458e3cad3/variant/compilers,5.5,p4spectec.0.1.0,lower-bounds)
    (failures when exploring builds with earlier versions of the dependencies)
  - [tests (failed: The compilation of p4spectec.0.1.0 failed at "dune build -p p4spectec -j 71 @install @runtest".)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/0ded330ca2bcf156ee9cdd6548cdadd458e3cad3/variant/compilers,5.5,p4spectec.0.1.0,tests)
    (test failures)

**Comment by pacokwon** [comment]
Closing, superceded by #30430
