### PR TITLE
gen_js_api no working with OCaml 5.3

### PR DESCRIPTION
**Pull request by hhugo**
See https://github.com/LexiFi/gen_js_api/pull/180

### CODE REVIEW

File: packages/gen_js_api/gen_js_api.1.0.7/opam [hunk 1]
```diff
@@ -19,7 +19,7 @@ homepage: "https://github.com/LexiFi/gen_js_api"
 bug-reports: "https://github.com/LexiFi/gen_js_api/issues"
 depends: [
   "dune" {>= "2.0"}
-  "ocaml" {>= "4.08"}
+  "ocaml" {>= "4.08" & < "5.3.0"}
   "ppxlib" {>= "0.9"}
```
Comment (mseri) [inline packages/gen_js_api/gen_js_api.1.0.7/opam]:
```suggestion
  "ppxlib" {>= "0.18"}
```

Comment (mseri) [reply packages/gen_js_api/gen_js_api.1.0.7/opam]: Due to 
```
# File "ppx-lib/gen_js_api_ppx.mli", line 5, characters 32-77:
# 5 | val mark_as_handled_manually : (Migrate_parsetree.Ast_411.Parsetree.attribute -> unit) ref
#                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# Error: Unbound module Migrate_parsetree.Ast_411
# Hint: Did you mean Ast_410?
```

**Comment by mseri** [comment]
Thanks

**Comment by mseri** [comment]
Thanks

**Comment by hhugo** [comment]
@mseri, maybe we went too fast with this one.
It turns out that it's the OCaml 5.3 + ppxlib.0.36 + gen_js_api combinaison that is problematic. Using it with ppxlib.0.35  seems fine.
