### ISSUE TITLE
shell v0.12.0 fails to build on OpenBSD 6.6

### ISSUE THREAD

**Issue by SenorAgosto** [ocaml/opam-repository#15741]
**shell v0.12.0** fail to build on OpenBSD 6.6.

The problem here is because `DEV_BSIZE` is defined in `sys/param.h` on BSD and this header is not being included in `unix_extended/src/unix_extended_stubs.c`.

Add the following before line 17:

    #include <sys/param.h>

## opam config report

    $ opam config report
    # opam config report
    # opam-version      2.0.5
    # self-upgrade      no
    # system            arch=x86_64 os=openbsd os-distribution=openbsd os-version=6.6
    # solver            builtin-mccs+glpk
    # install-criteria  -removed,-count[version-lag,request],-count[version-lag,changed],-changed   
    # upgrade-criteria  -removed,-count[version-lag,solution],-new
    # jobs              1
    # repositories      1 (http) (default repo at ef627cdd)
    # pinned            4 (git)
    # current-switch    ocaml-system.4.09.0

## opam output 

In https://github.com/comby-tools/comby directory, run `opam install --deps-only -y`

    #=== ERROR while compiling shell.v0.12.0 ======================================#
    # context     2.0.5 | openbsd/x86_64 | ocaml-system.4.09.0 | https://opam.ocaml.org#ef627cdd 
    # path        ~/.opam/ocaml-system.4.09.0/.opam-switch/build/shell.v0.12.0
    # command     ~/.opam/ocaml-system.4.09.0/bin/dune build -p shell -j 1
    # exit-code   1
    # env-file    ~/.opam/log/shell-8994-dc6e87.env
    # output-file ~/.opam/log/shell-8994-dc6e87.out
    ### output ###
    # unix_extended_stubs.c:196:63: error: use of undeclared identifier 'DEV_BSIZE'
    # [...]
    #                                                               ^
    # unix_extended_stubs.c:99:38: note: expanded from macro 'QUOTA_BYTES_PER_SPACE_UNIT'
    # #  define QUOTA_BYTES_PER_SPACE_UNIT DEV_BSIZE
    #                                      ^
    # unix_extended_stubs.c:197:63: error: use of undeclared identifier 'DEV_BSIZE'
    #   quota.dqb_bhardlimit = Int63_val(Field(v_bytes_limit, 1)) / QUOTA_BYTES_PER_SPACE_UNIT; 
    #                                                               ^
    # unix_extended_stubs.c:99:38: note: expanded from macro 'QUOTA_BYTES_PER_SPACE_UNIT'
    # #  define QUOTA_BYTES_PER_SPACE_UNIT DEV_BSIZE
    #                                      ^
    # 5 errors generated.

**Comment by kit-ty-kate** [comment]
This should not be reported here. Could you please report it in the correct bugtracker: https://github.com/janestreet/shell

The only thing we can do is to prevent installation of this package on openbsd by marking it incompatible, however there might be a particular version where this might work and I don't have enough knowledge with openbsd

**Comment by SenorAgosto** [comment]
> This should not be reported here. Could you please report it in the correct bugtracker: https://github.com/janestreet/shell
> 
> The only thing we can do is to prevent installation of this package on openbsd by marking it incompatible, however there might be a particular version where this might work and I don't have enough knowledge with openbsd

Done. https://github.com/janestreet/shell/issues/1#issue-565839668
