### PR TITLE
[new release] goblint (2.3.0)

### PR DESCRIPTION
**Pull request by sim642**
Static analysis framework for C

- Project page: <a href="https://goblint.in.tum.de">https://goblint.in.tum.de</a>
- Documentation: <a href="https://goblint.readthedocs.io/en/latest/">https://goblint.readthedocs.io/en/latest/</a>

##### CHANGES:

Functionally equivalent to Goblint in SV-COMP 2024.

* Add termination analysis for loops (goblint/analyzer#1093).
* Add memory out-of-bounds analysis (goblint/analyzer#1094, goblint/analyzer#1197).
* Add memory leak analysis (goblint/analyzer#1127, goblint/analyzer#1241, goblint/analyzer#1246).
* Add SV-COMP `termination`, `valid-memsafety` and `valid-memcleanup` properties support (goblint/analyzer#1220, goblint/analyzer#1228, goblint/analyzer#1201, goblint/analyzer#1199, goblint/analyzer#1259, goblint/analyzer#1262).
* Add YAML witness version 2.0 support (goblint/analyzer#1238, goblint/analyzer#1240, goblint/analyzer#1217, goblint/analyzer#1226, goblint/analyzer#1225, goblint/analyzer#1248).
* Add final warnings about unsound results (goblint/analyzer#1190, goblint/analyzer#1191).
* Add many library function specifications (goblint/analyzer#1167, goblint/analyzer#1174, goblint/analyzer#1203, goblint/analyzer#1205, goblint/analyzer#1212, goblint/analyzer#1220, goblint/analyzer#1239, goblint/analyzer#1242, goblint/analyzer#1244, goblint/analyzer#1254, goblint/analyzer#1269).
* Adapt automatic configuration tuning (goblint/analyzer#912, goblint/analyzer#921, goblint/analyzer#987, goblint/analyzer#1168, goblint/analyzer#1214, goblint/analyzer#1234).

### CODE REVIEW

**Comment by sim642** [comment]
CI failures:

1. freebsd:

   ```
   #=== ERROR while compiling conf-ruby.1.0.0 ====================================#
   "ruby": command not found.
   ```
   I guess conf-ruby doesn't have a depext for FreeBSD.

2. macos-homebrew: (from goblint-cil)

   ```
   # /usr/local/Cellar/gcc/13.2.0/lib/gcc/current/gcc/x86_64-apple-darwin23/13/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
   #    78 | #include <_stdio.h>
   #       |          ^~~~~~~~~~
   ```
   Same failure as mentioned in https://github.com/ocaml/opam-repository/pull/24812#issuecomment-1819231335.

**Review by haochenx — APPROVED** [review]
All looks good to me and CI failures are not blocks (as explained by the author)

**Comment by mseri** [comment]
Thanks
