### PR TITLE
[new release] io-page, io-page-unix and io-page-xen (2.2.0)

### PR DESCRIPTION
**Pull request by samoht**
Support for efficient handling of I/O memory pages

- Project page: <a href="https://github.com/mirage/io-page">https://github.com/mirage/io-page</a>
- Documentation: <a href="https://mirage.github.io/io-page/">https://mirage.github.io/io-page/</a>

##### CHANGES:

* Use bigarray_compat (mirage/io-page#56, @TheLortex)

### CODE REVIEW

**Comment by samoht** [comment]
Hum `discover.ml` doesn't work on 4.02:

```
#=== ERROR while compiling io-page-xen.2.2.0 ==================================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.02.3 | file:///home/travis/build/ocaml/opam-repository
# path        ~/.opam/ocaml-base-compiler.4.02.3/.opam-switch/build/io-page-xen.2.2.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build env OPAM_PKG_CONFIG_PATH=/home/travis/.opam/ocaml-base-compiler.4.02.3/lib/pkgconfig dune build -p io-page-xen -j 1
# exit-code   1
# env-file    ~/.opam/log/io-page-xen-18342-335865.env
# output-file ~/.opam/log/io-page-xen-18342-335865.out
### output ###
#       ocamlc lib/config/.discover.eobjs/byte/discover.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/travis/.opam/ocaml-base-compiler.4.02.3/bin/ocamlc.opt -w -40 -g -bin-annot -I lib/config/.discover.eobjs/byte -I /home/travis/.opam/ocaml-base-compiler.4.02.3/lib/dune/_caml -I /home/travis/.opam/ocaml-base-compiler.4.02.3/lib/dune/_dune_lang -I /home/travis/.opam/ocaml-base-compiler.4.02.3/lib/dune/_ocaml_config -I /home/travis/.opam/ocaml-base-compiler.4.02.3/li[...]
# File "lib/config/discover.ml", line 9, characters 9-21:
# Error: Unbound value String.equal
```

It's probably just fine to restrict the package to '> 4.02'.

File: packages/io-page-xen/io-page-xen.2.2.0/opam [hunk 1]
```diff
@@ -0,0 +1,34 @@
+opam-version: "2.0"
+maintainer: "anil@recoil.org"
+authors: ["Anil Madhavapeddy" "Dave Scott" "Thomas Gazagnaire"]
+license: "ISC"
+tags: "org:mirage"
+homepage: "https://github.com/mirage/io-page"
+bug-reports: "https://github.com/mirage/io-page/issues"
+doc: "https://mirage.github.io/io-page/"
+depends: [
+  "ocaml" {>= "4.02.3"}
```
Comment (samoht) [inline packages/io-page-xen/io-page-xen.2.2.0/opam]:
```suggestion
  "ocaml" {>= "4.03.0"}
```

**Comment by avsm** [comment]
That constraint is fine, thanks!
