### PR TITLE
added packages/bst/bst.3.0.0

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
There is a missing dep on `parmap` apparently:
```
#=== ERROR while installing bst.3.0.0 =========================================#
# opam-version         1.2.2 (aa258ecc06d3aea5a67f442a4ffd23f2a457180b)
# os                   linux
# command              jbuilder build -p bst -j 2
# path                 /home/opam/.opam/4.05.0/build/bst.3.0.0
# compiler             4.05.0
# exit-code            1
# env-file             /home/opam/.opam/4.05.0/build/bst.3.0.0/bst-7-d2c37b.env
# stdout-file          /home/opam/.opam/4.05.0/build/bst.3.0.0/bst-7-d2c37b.out
# stderr-file          /home/opam/.opam/4.05.0/build/bst.3.0.0/bst-7-d2c37b.err
### stderr ###
# File "jbuild", line 7, characters 14-20:
# Error: Library "parmap" not found.
# Hint: try: jbuilder external-lib-deps --missing -p bst @install
```

**Comment by UnixJunkie** [comment]
I'll have to retag, this is due to some left over thing in the jbuild file.

**Comment by kit-ty-kate** [comment]
All green except 4.02. Could you constrain it to OCaml >= 4.03 ?
```
#=== ERROR while installing bst.3.0.0 =========================================#
# opam-version 1.2.2
# os           linux
# command      jbuilder build -p bst -j 4
# path         /home/travis/.opam/system/build/bst.3.0.0
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/bst.3.0.0/bst-7490-e7966f.env
# stdout-file  /home/travis/.opam/system/build/bst.3.0.0/bst-7490-e7966f.out
# stderr-file  /home/travis/.opam/system/build/bst.3.0.0/bst-7490-e7966f.err
### stderr ###
#       ocamlc .bst.objs/bst__Bisec_tree.{cmo,cmt} (exit 2)
# (cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -bin-annot -I .bst.objs -no-alias-deps -open Bst -o .bst.objs/bst__Bisec_tree.cmo -c -impl bisec_tree.ml)
# File "bisec_tree.ml", line 400, characters 6-15:
# Error: Unbound value A.for_all
#     ocamlopt .bst.objs/bst__Bisec_tree.{cmx,o} (exit 2)
# (cd _build/default && /usr/bin/ocamlopt.opt -w -40 -g -I .bst.objs -no-alias-deps -open Bst -o .bst.objs/bst__Bisec_tree.cmx -c -impl bisec_tree.ml)
# File "bisec_tree.ml", line 400, characters 6-15:
# Error: Unbound value A.for_all
```

**Comment by UnixJunkie** [comment]
I will make it compile on 4.02.3,
There is no reason it should not compile where jbuilder is compiling.

**Comment by UnixJunkie** [comment]
There are two strange errors left in there:
https://travis-ci.org/ocaml/opam-repository/builds/385497982?utm_source=github_status&utm_medium=notification
but I think they are CI-test-related.
So, this PR is as good to me as I can make it.

**Comment by kit-ty-kate** [comment]
Yes there were temporary failures. I relaunched them and now it's all green. Thanks a lot !
