### PR TITLE
future.0.2.0: add upper bound on version of solvuu-build

### PR DESCRIPTION
**Pull request by damiendoligez**
`future` doesn't compile with `solvuu-build` 0.3.0 (API change).

cc @agarwal

### CODE REVIEW

**Comment by agarwal** [comment]
Thanks for the fix. I'll release a new version of future to bring it up to date.

**Comment by samoht** [comment]
There seem to some compilation errors on some distros, but merging as it improves the current state anyway. @agarwal could you have a look for the next releases? Thanks!

**Comment by agarwal** [comment]
> There seem to some compilation errors on some distros

Where can I see this?

**Comment by samoht** [comment]
https://ci.ocaml.io/ocaml/opam-repository/pr/8884?history=5e8520e4455eea437f0bf1323ae704ddb9579ca0&test=4%20V2.0%20Common%20Distros

**Comment by samoht** [comment]
e.g. https://ci.ocaml.io/log/saved/docker-build-46db0e90a545965491684d1a7f83aaa6/3a5d3ebd58c17ade6b9d03b7190ac92db198bf35
