### PR TITLE
[new release] cohttp (14 packages) (6.2.0)

### PR DESCRIPTION
**Pull request by samoht**
An OCaml library for HTTP clients and servers

- Project page: <a href="https://github.com/mirage/ocaml-cohttp">https://github.com/mirage/ocaml-cohttp</a>
- Documentation: <a href="https://mirage.github.io/ocaml-cohttp/">https://mirage.github.io/ocaml-cohttp/</a>

##### CHANGES:

- cohttp-eio: Add support for forward proxies to the client (@shonfeder,  mirage/ocaml-cohttp#1126)
- cohttp-lwt: Expose the IO module, allowing IO errors to be handled (@mefyl, mirage/ocaml-cohttp#1118)

### CODE REVIEW

**Comment by shonfeder** [comment]
Windows failures are issues fetching dependency sources, and some jobs are succeeding OK on libraries, so I don't think any indication of trouble here.

File: packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.6.2.0/opam [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+doc: "https://mirage.github.io/ocaml-cohttp/"
+bug-reports: "https://github.com/mirage/ocaml-cohttp/issues"
+depends: [
+  "dune" {>= "3.8"}
+  "ocaml" {>= "4.08"}
+  "http" {= version}
+  "cohttp" {= version}
+  "cohttp-lwt" {= version}
+  "logs"
+  "lwt" {>= "3.0.0"}
```
Comment (avsm) [inline packages/cohttp-lwt-jsoo/cohttp-lwt-jsoo.6.2.0/opam]:
```suggestion
  "lwt" {>= "5.7.0"}
```

for Lwt.reraise

File: packages/cohttp-lwt/cohttp-lwt.6.2.0/opam [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+license: "ISC"
+homepage: "https://github.com/mirage/ocaml-cohttp"
+doc: "https://mirage.github.io/ocaml-cohttp/"
+bug-reports: "https://github.com/mirage/ocaml-cohttp/issues"
+depends: [
+  "dune" {>= "3.8"}
+  "ocaml" {>= "4.08"}
+  "http" {= version}
+  "cohttp" {= version}
+  "lwt" {>= "5.4.0"}
```
Comment (shonfeder) [inline packages/cohttp-lwt/cohttp-lwt.6.2.0/opam]:
```suggestion
  "lwt" {>= "5.7.0"}
```

lower-bounds checks in CI are failing on 

```
# File "cohttp-lwt/src/connection_cache.ml", line 152, characters 17-28:
# 152 |           | e -> Lwt.reraise e)
#                        ^^^^^^^^^^^
# Error: Unbound value Lwt.reraise
```

And reraise was apparently added in 5.7: 

https://github.com/ocsigen/lwt/blob/8baa610a49f7cbc9a1834791809ab1feb3cef202/CHANGES#L73C7-L95

File: packages/cohttp/cohttp.6.2.0/opam [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+  "uri" {>= "2.0.0"}
+  "uri-sexp"
+  "logs"
+  "sexplib0"
+  "ppx_sexp_conv" {>= "v0.13.0"}
+  "stringext"
+  "base64" {>= "3.1.0"}
+  "fmt" {with-test}
+  "ipaddr" {>= "5.6.0"}
+  "alcotest" {with-test & >= "1.7.0"}
```
Comment (shonfeder) [inline packages/cohttp/cohttp.6.2.0/opam:49]: CI is failing with

```
- File "cohttp/test/test_proxy.ml", line 27, characters 12-18:
- 27 |   Alcotest.(check' @@ option proxy)
-                  ^^^^^^
- Error: This expression has type
-          ('a Alcotest.testable ->
-           msg:string -> expected:'a -> actual:'a -> unit)
-          Alcotest.extra_info =
-            ?here:Alcotest.Source_code_position.here ->
-            ?pos:Alcotest.Source_code_position.pos ->
-            'a Alcotest.testable ->
-            msg:string -> expected:'a -> actual:'a -> unit
-        but an expression was expected of type 'b -> 'c
- (cd _build/default/cohttp/test && ./test_body.exe)
```

https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/compilers,4.08,cohttp.6.2.0,tests

for all compiler versions before 4.13 .

In context, this code looks like

```ocaml
let select_http_proxy () =
  let proxies = proxies ~no_proxy_patterns:None in
  let expected = Some (Proxy.Direct http_proxy) in
  let actual = Proxy.get proxies @@ Uri.of_string "http://example.com" in
  Alcotest.(check' @@ option proxy)
    ~msg:"should select configured http proxy as Direct" ~actual ~expected
```

so older versions must not be able to handle the inference for partially applied function taking labeled arguments.

I don't think we want to increase the required compiler version for the test dependency tho, so I suppose this will need a patch and new release. (I introduced this code, and I will get that fix underway.)

File: packages/cohttp-async/cohttp-async.6.2.0/opam [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+license: "ISC"
+homepage: "https://github.com/mirage/ocaml-cohttp"
+doc: "https://mirage.github.io/ocaml-cohttp/"
+bug-reports: "https://github.com/mirage/ocaml-cohttp/issues"
+depends: [
+  "dune" {>= "3.8"}
+  "ocaml" {>= "4.14" & < "5.3.0"}
+  "http" {= version}
+  "cohttp" {= version}
+  "async_kernel" {>= "v0.16.0"}
```
Comment (shonfeder) [inline packages/cohttp-async/cohttp-async.6.2.0/opam]:
```suggestion
  "async_kernel" {>= "v0.17.0"}
```

CI error

```
#=== ERROR while compiling cohttp-async.6.2.0 =================================#
...
# File "cohttp-async/src/client.ml", line 113, characters 8-21:
# 113 |         Ivar.fill_exn res (resp, `Pipe body);
#               ^^^^^^^^^^^^^
# Error: Unbound value Ivar.fill_exn
```

https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/compilers,4.14,cohttp-async.6.2.0

introduced in https://github.com/mirage/ocaml-cohttp/commit/27c853d8c33d66d9911ad3fa9c005b904699575b

and IIUC, not available unitl v0.71.0, as per https://github.com/janestreet/async_kernel/commit/e717283f379b8ee410c371e6080da091a1660c69#diff-2afa00a94d30eaeaf0374e7bb64ee636514d6f4123bdeb24524fa598e214dbe5R24-R27

**Review by shonfeder — CHANGES_REQUESTED** [review]
I think I've identified all issues with dependencies in this release.

We will also need at least one upper bounds on revdeps (tho many apparent revdeps failures are actually just due to the lower bounds issue with `Ivar.fill_exn`).

## [opentelemetry-cohttp-lwt](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/compilers,4.14,cohttp-lwt.6.2.0,revdeps,opentelemetry-cohttp-lwt.0.12)

```
#=== ERROR while compiling opentelemetry-cohttp-lwt.0.12 ======================#

# File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 233, characters 10-16:
# 233 |   (module Traced : Cohttp_lwt.S.Client)
#                 ^^^^^^
# Error: Signature mismatch:
#        ...
#        The module `IO' is required but not provided
#        File "cohttp-lwt/src/s.ml", line 196, characters 2-42:
#          Expected declaration
```

due to the `IO` module now being required by clients: https://github.com/mirage/ocaml-cohttp/pull/1118/files#diff-39e91802bd01e21cce657097de614f52810d046d7243f0c61f71351fa7ff91c0R196-R197

---

There is also the following test failures


On https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/compilers,5.0,cohttp-lwt-unix.6.2.0,tests):

```
# File "cohttp-lwt-unix/test/dune", lines 22-26, characters 0-86:
# 22 | (rule
# 23 |  (alias runtest)
# 24 |  (package cohttp-lwt-unix)
# 25 |  (action
# 26 |   (run ./test_sanity.exe)))
# (cd _build/default/cohttp-lwt-unix/test && ./test_sanity.exe)
# ....E.
# ==============================================================================
# Error: Cohttp Server Test:4:no leaks on requests
# 
# Failure("Test produced 1 log messages at level >= warn")
# ------------------------------------------------------------------------------
# Ran: 6 tests in: 0.02 seconds.
# FAILED: Cases: 6 Tried: 6 Errors: 1 Failures: 0 Skip:  0 Todo: 0 Timeouts: 0.
# [DEBUG][application]: Cohttp debugging output is active
# [WARNING][cohttp.lwt.client]: Body not consumed, leaking stream! Refer to https://github.com/mirage/ocaml-cohttp/issues/730 for additional details
```


On MacOS

> macos-homebrew-ocaml-4.14-amd64 (experimental)
        [cohttp-async.6.2.0 (failed: Unbound value Ivar.fill_exn)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-4.14-amd64,cohttp-async.6.2.0)
        cohttp-curl-lwt.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-4.14-amd64,cohttp-curl-lwt.6.2.0,tests)
        cohttp-lwt-unix.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-4.14-amd64,cohttp-lwt-unix.6.2.0,tests)
    macos-homebrew-ocaml-4.14-arm64 (experimental)
        [cohttp-async.6.2.0 (failed: Unbound value Ivar.fill_exn)](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-4.14-arm64,cohttp-async.6.2.0)
        cohttp-curl-lwt.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-4.14-arm64,cohttp-curl-lwt.6.2.0,tests)
        cohttp-lwt-unix.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-4.14-arm64,cohttp-lwt-unix.6.2.0,tests)
    macos-homebrew-ocaml-5.4-amd64 (experimental)
        cohttp-curl-lwt.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-5.4-amd64,cohttp-curl-lwt.6.2.0,tests)
        cohttp-eio.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-5.4-amd64,cohttp-eio.6.2.0,tests)
        cohttp-lwt-unix.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-5.4-amd64,cohttp-lwt-unix.6.2.0,tests)
    macos-homebrew-ocaml-5.4-arm64 (experimental)
        cohttp-curl-lwt.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-5.4-arm64,cohttp-curl-lwt.6.2.0,tests)
        cohttp-eio.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-5.4-arm64,cohttp-eio.6.2.0,tests)
        cohttp-lwt-unix.6.2.0
            [tests (failed: exception Unix.Unix_error(Unix.EPERM, "bind", ""))](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/55e0b8b5e2bab4f6002f90a3c622cfa3aa91e549/variant/macos,macos-homebrew-ocaml-5.4-arm64,cohttp-lwt-unix.6.2.0,tests)

```
#=== ERROR while compiling cohttp-curl-lwt.6.2.0 ==============================#
# context              2.4.1 | macos/x86_64 | ocaml-base-compiler.4.14.2 | pinned(https://github.com/mirage/ocaml-cohttp/releases/download/v6.2.0/cohttp-6.2.0.tbz)
# path                 ~/.opam/4.14.2/.opam-switch/build/cohttp-curl-lwt.6.2.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cohttp-curl-lwt -j 11 @install @cohttp-curl-lwt/runtest
# exit-code            1
# env-file             ~/.opam/log/cohttp-curl-lwt-74606-7e4566.env
# output-file          ~/.opam/log/cohttp-curl-lwt-74606-7e4566.out
### output ###
# File "cohttp-curl-lwt/test/dune", line 2, characters 7-28:
# 2 |  (name cohttp_curl_lwt_tests)
#            ^^^^^^^^^^^^^^^^^^^^^
# (cd _build/default/cohttp-curl-lwt/test && ./cohttp_curl_lwt_tests.exe)
# [DEBUG][application]: Cohttp debugging output is active
# [INFO][application]: Test Cohttp Server Test running on http://localhost:25190
# [INFO][application]: Running simple request
# [INFO][application]: Running failing request
# Fatal error: exception Unix.Unix_error(Unix.EPERM, "bind", "")
```

File: packages/cohttp/cohttp.6.2.0/opam (hunk 3 above)
Comment (avsm) [reply packages/cohttp/cohttp.6.2.0/opam:49]: This is because of the @@ and labels; https://github.com/ocaml/ocaml/pull/10081

Comment (shonfeder) [reply packages/cohttp/cohttp.6.2.0/opam:49]: Thanks for the pointer!

**Comment by shonfeder** [comment]
I've proposed a fix for the blocking issue (IMO), which is loss of support for OCaml =< 4.12 due to a discretionary syntax choice in a new test suite. This is in https://github.com/mirage/ocaml-cohttp/pull/1135. 

I propose we close this and cut a new patch release for that fix. What do you think, @samoht ?

This regression was my fault: I am sorry for the trouble.

**Comment by shonfeder** [comment]
Replaced by https://github.com/ocaml/opam-repository/pull/29100
